config/routes.rb
Rails.application.routes.draw do

  get 'sitemap/index'

  get 'message_photos/create'

  root                                'static_pages#home'
  get    'help'                    => 'static_pages#help'
  get    'about'                   => 'static_pages#about'
  get    'how-it-works'            => 'static_pages#how_it_works'
  get    'dashboard'               => 'static_pages#dashboard'
  get    'tour'                    => 'static_pages#tour'
  get    'legal'                   => 'static_pages#legal'
  get    'feed_0'                  => 'vehicles#feed_0'
  get    'feed_1'                  => 'vehicles#feed_1'
  get    'feed_2'                  => 'vehicles#feed_2'
  get    'feed_3'                  => 'vehicles#feed_3'
  get    'feed_4'                  => 'vehicles#feed_4'
  get    'feed_5'                  => 'vehicles#feed_5'
  get    'feed_6'                  => 'vehicles#feed_6'
  get    'feed_7'                  => 'vehicles#feed_7'
  get    'feed_8'                  => 'vehicles#feed_8'
  get    'feed_9'                  => 'vehicles#feed_9'
  get    'feed_10'                 => 'vehicles#feed_10'
  get    'feed_11'                 => 'vehicles#feed_11'
  get    'feed_12'                 => 'vehicles#feed_12'
  get    'feed_13'                 => 'vehicles#feed_13'
  get    'feed_14'                 => 'vehicles#feed_14'
  get    'feed_15'                 => 'vehicles#feed_15'
  get    'feed_16'                 => 'vehicles#feed_16'
  get    'feed_17'                 => 'vehicles#feed_17'
  get    'feed_18'                 => 'vehicles#feed_18'
  get    'feed_19'                 => 'vehicles#feed_19'
  get    'feed_20'                 => 'vehicles#feed_20'
  get    'feed_21'                 => 'vehicles#feed_21'
  get    'feed_22'                 => 'vehicles#feed_22'
  get    'feed_23'                 => 'vehicles#feed_23'
  get    'feed_24'                 => 'vehicles#feed_24'
  get    'feed_25'                 => 'vehicles#feed_25'
  get    'admin'                   => 'dealerships#admin'
  get    'customers'               => 'appointments#customers'
  get    'test-drives'             => 'appointments#test_drives'
  get    'purchases_made'          => 'purchases#purchases_made'
  get    'orders_received'         => 'purchases#orders_received'
  # get    'start_personalized_search' => 'personalized_searches#start'
  get    'payment_method'          => 'users#payment'
  get    'payout_method'           => 'users#payout'
  get    'signup'                  => 'users#new'
  get    'login'                   => 'sessions#new'
  get    'auth/:provider/callback' => 'sessions#create_social'
  get    'sitemap-nav'             => 'sitemap#sitemap_nav'
  get    'sitemap-vehicles_0'      => 'sitemap#sitemap_vehicles_0.xml'
  get    'sitemap-vehicles_1'      => 'sitemap#sitemap_vehicles_1'
  get    'sitemap-vehicles_2'      => 'sitemap#sitemap_vehicles_2'
  get    'sitemap-vehicles_3'      => 'sitemap#sitemap_vehicles_3'
  get    'sitemap_vehicle_makes'   => 'sitemap#sitemap_vehicle_makes'
  get    'sitemap_discussions'     => 'sitemap#sitemap_discussions'
  get    'sitemap_posts'           => 'sitemap#sitemap_posts'
  get    'sitemap_dealerships'     => 'sitemap#sitemap_dealerships'
  get    'sitemap_clubs'           => 'sitemap#sitemap_clubs'
  post   'login'                   => 'sessions#create'
  post   'password'                => 'sessions#create'
  post   'upload'                  => 'vehicles#upload'
  post   'add_card'                => 'users#add_card'
  delete 'logout'                  => 'sessions#destroy'
  
  resources :autopart_photos
  resources :message_photos
  resources :blogs
  resources :account_activations,    only: [:edit]
  resources :dealership_activations, only: [:edit]
  resources :password_resets,        only: [:new, :create, :edit, :update]
  resources :enquiries,              only: [:new, :create]
  resources :profiles,               only: [:show, :edit, :update]
  resources :sitemap,                only: [:index]

  resources :articles do
    collection do
      get 'insurance'
      get 'parts_and_accessories'
      get 'legal'
      get 'loans_and_financing'
      get 'motorcycle_repair'
      get 'motorcycle_tours_and_rentals'
      get 'shipping'
      get 'warranties_and_roadside_assistance'
    end
  end

  resources :vehicle_makes, path: "motorcycle_makes" do
    member do
      get 'posts'
      get 'discussions'
    end
  end
  
  resources :clubs do
    
    resources :club_products
    resources :invitations
   
    member do
      
      get 'posts'
      get 'discussions'
      
      put :join
    end
    
    collection do
      get 'search'
      get :autocomplete
    end
  end
  
  resources :users do
    
    resources :reviews, only: [:index, :destroy]
    
    # resource :personalized_search do
    #   member do
    #     get 'price'
    #     get 'mileage'
    #     get 'year'
    #     get 'installed_options'
    #     get 'summary'
    #   end
    # end

    member do
      get 'password'
      get 'profile_pic'
      get 'profile_pic_dealer'
      get 'dealer_details'
      get 'shortlist'
    end
  end

  resources :vehicles, path: "motorcycles" do
    
    resources :reviews,  only: [:create, :destroy]
    resources :payments, only: [:new, :create]
    
    # put :favorite, on: :member
    # put :sold,     on: :member
    
    member do
      
      put :post
      put :favorite
      put :unfavorite
      put :sold
      put :undo_sold
      put :bump
      
      get 'basics'
      get 'details'
      get 'photos'
      get 'about_you'
      get 'consumer_activity'
    end
    
    collection do
      get 'search'
      get :autocomplete
    end
    
    resources :appointments, only: [:new, :create, :destroy] do
      member do
        put :accept
        put :decline
      end
    end
    
    resources :photos, only: [:create, :destroy] do
      member do
        put :rotate
      end
    end
  end
  
  resources :vehicles_for_sale, path: "motorcycles_for_sale" do
    collection do
      get 'san_francisco'
      get 'oakland'
      get 'san_jose'
      get 'los_angeles'
      get 'long_beach'
      get 'san_diego'
      get 'cafe_racer'
      get 'cruisers'
      get 'dirt_bike'
      get 'dual_sport'
      get 'mini_pocket'
      get 'moped'
      get 'sportbike'
      get 'standard'
      get 'touring'
      get 'trike'
      get 'aprilia'
      get 'bmw'
      get 'can_am'
      get 'ducati'
      get 'harley_davidson'
      get 'honda'
      get 'indian'
      get 'kawasaki'
      get 'ktm'
      get 'kymco'
      get 'suzuki'
      get 'triumph'
      get 'vespa'
      get 'victory'
      get 'yamaha'
    end
  end
  
  resources :dealerships do
    
    resources :dealer_invitations
    resources :reviews, only: :destroy
    
    member do
      get 'authentication'
      get 'basics'
      get 'about'
      get 'contact'
      get 'hours'
      get 'address'
      get 'logo'
      get 'photo'
      get 'vehicles'
      get 'reviews'
      get 'performance'
      get 'inventory'
    end
  end

  resources :conversations, only: [:index, :create] do
    
    resources :appointments, only:   [:new, :create, :destroy]
    resources :messages,     except: [:new, :edit, :show, :update]
    
    member do
      put :archive
      put :reveal_identity
      put :hide_identity
      get 'export'
    end
  end
  
  resources :discussions do
    
    resources :discussion_comments
    
    member do
      get :like,   to: "discussions#like"
      get :unlike, to: "discussions#unlike"
    end
    
    collection do
      get 'search'
      get :autocomplete
    end
  end
  
  resources :posts do
    
    resources :post_comments
    
    member do
      get :like,   to: "posts#like"
      get :unlike, to: "posts#unlike"
    end
  end
  
  resources :autoparts do
    member do
      put :favorite
      put :sold
      put :undo_sold
      put :bump
    end
  end
  
  resources :purchases do
    member do
      
      put :submit
      
      get 'order'
      get 'basics'
      get 'details'
      get 'billing'
      get 'employment'
      get 'financial'
    end
  end
  
  resources :personalized_searches do
    
    collection do
      get 'start'
      get 'survey'
    end
    
    member do
      
      put :all_manufacturers
      
      get 'style'
      get 'manufacturer'
      get 'price'
      get 'mileage'
      get 'location'
    end
  end
  
  # match "conversations/:id/messages/accept" => "conversations#messages#accept", :as => "conversation_messages_accept_path"
  
  # match "conversations/:id/messages/decline" => "conversations#messages#decline", :as => "conversation_messages_decline_path"
end

app/models/club_product.rb
class ClubProduct < ActiveRecord::Base
  
  belongs_to :club
  
  has_many :club_product_photos, dependent: :destroy
  
  validates :price, :description, :club_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  
  # Removes spaces and commas from price and mileage.
  
  def price=(val)
    write_attribute :price, val.to_s.gsub(/[\s,]/, '').to_i
  end
end

app/controllers/club_products_controller.rb
class ClubProductsController < ApplicationController
  
  before_action :logged_in_user,   except: [:show, :index]
  before_action :get_club,         only:   [:new, :create, :index]
  before_action :get_club_product, only:   [:show]
  
  # before_action :profile_pic, :club_admin
  
  def new
    # @club_product = @club.club_products.build
  end
  
  def create
    
    @club_product = @club.club_products.build(club_product_params)
    
    if @club_product.save
      
      if params[:images]
        params[:images].each do |image|
          @club_product.club_product_photos.create(image: image)
        end
      end
      
      @club_product_photos = @club_product.club_product_photos
      flash[:success] = "Product has been posted"
      redirect_to [@club, @club_product]
    
    else
      render 'new'
    end
  end
  
  def update
  end
  
  def show
  end
  
  def index
  end
  
  private
  
    def club_product_params
      params.require(:club_product).permit(:name, :price, :description, 
                                           :shipping_info)
    end
  
    # Before filters
    
    # Identifies autopart id
    
    def get_club
      @club = Club.find(params[:club_id])
    end
    
    def get_club_product
      @club_product = ClubProduct.find(params[:id])
    end
end

app/views/club_products/_club_product.html.erb
<li>
  <%= link_to club_product.name %>
</li>

app/views/club_products/_form.html.erb
<%= form_for([@club, @club.club_products.build], 
             html: { multipart: true }) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div class="basics">
    <div class="row">
      
      <div class="col-md-4">
        
        <h2 class="basics-title">The Basics</h2>
        
        <p class="basics-info">
          Start with the basics.
        </p>
      </div>
      
      <div class="col-md-8">
        
        <div class="row">
          
          <div class="col-md-6 form-group">

            <%= f.label :price %>
            
            <div class= "input-group">
              
              <div class="input-group-addon">$</div>
              
              <%= f.text_field :price, 
                               placeholder: "Eg. 400", 
                               class: "form-control form-control-primary" %>
            </div>
          </div>

          <div class="col-md-6">
            <!--intentionally left empty-->
          </div>
        </div>
        
        <div class="form-group">
          
          <%= f.label :name, "Listing Name" %>
          
          <%= f.text_field :name, 
                           placeholder: "Eg. Dodge Dakota Truck Cap", 
                           class: "form-control form-control-primary" %>
        </div>
        
        <div class="form-group">
          
          <%= f.label :description %>
          
          <%= f.text_area :description, 
                          rows: 3,
                          placeholder: "Eg. Features tinted windows and full-length side doors.", 
                          class: "form-control form-control-primary" %>
        </div>
        
        <div class="form-group">
          
          <%= f.label :shipping_info, "Shipping Details" %>
          
          <%= f.text_area :shipping_info,
                          rows: 3,
                          placeholder: "Enter shipping details if part can be mailed (optional).", 
                          class: "form-control form-control-primary" %>
        </div>
        
        <div id="autopart-photos">
          <%= render 'autopart_photos/list' %>
        </div>
        
        <span class="btn btn-green btn-file">
              
              Select Photos
              
              <%= file_field_tag "images[]", 
                               type: :file, 
                               multiple: true %>
            </span>
      </div>
    </div>
  </div>
  
  <div class="row submit-vehicle">
    
    <div class="col-md-4">
      <!--intentionally left blank-->
    </div>
    
    <div class="col-md-8">
      <%= f.submit "Submit Details", class: "submit btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/club_products/index.html.erb
<% provide(:title, @club.name) %>

<header class="header-static-gray">
  <%= render 'layouts/header_secondary' %>
</header>

<%= render 'layouts/modal_search' %>

<%= render 'layouts/modal_menu' %>

<div class="club-profile-hero">
  <div class="club-profile-hero-content">
    <div class="row">
      
      <div class="col-md-8 col-md-push-4">
        <div class="club-profile-hero-photo" 
             style="background-image: url('<%= @club.cover_photo.url() %>')">
          <div class="club-profile-hero-caption-container visible-xs">
            <span class="club-profile-hero-caption">
              <%= @club.city %>, <%= @club.state %>
            </span>
          </div>
        </div>
      </div>
      
      <div class="col-md-4 col-md-pull-8">
        <div class="club-profile-hero-text">
        
          <ol class="club-profile-hero-nav">
            
            <li><%= link_to "Community Center", discussions_path %></li>
            
            <li>
              
              <i class="fa fa-angle-right club-profile-hero-nav-separator"
                 aria-hidden="true"></i>
                 
              <%= link_to "Car Clubs", clubs_path %>
            </li>
          </ol>
          
          <h1 class="club-profile-hero-title"><%= @club.name %></h1>
          
          <p class="club-profile-hero-info"><%= @club.description %></p>
          
          <span class="club-profile-hero-expand">+ More</span>
          
          <% if logged_in? && 
                current_user.
                  memberships.
                  where(club_id: @club.id, admin: true).
                  exists? %>
                  
            <!--<= link_to "Update", edit_club_path %>-->
            
            <!--<(perc)= link_to "Add A Product", new_club_club_product_path(@club) %>-->
            
            <%= link_to new_club_invitation_path(@club),
                        class: "btn btn-club-invitation" do %>
              
              <i class="fa fa-paper-plane club-invitation-icon" 
                 aria-hidden="true"></i>
              
              Send Invitations
            <% end %>
            
          <% elsif logged_in? && 
                   Invitation.where(email: current_user.email).exists? &&
                   !current_user.
                     memberships.
                     where(club_id: @club.id).
                     exists? %>
          
            <%= link_to join_club_path(@club), 
                        method: :put,
                        class: "btn btn-club-join" do %>
              
              <i class="fa fa-user-plus club-join-icon" 
                 aria-hidden="true"></i>
              
              Join Club
            <% end %>          
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="club-profile-navbar hidden-xs">
  <div class="club-profile-navbar-content">
    <div class="row">
    
      <div class="col-md-8">
        <nav>
          <ul class="nav navbar-nav navbar-left">
            
            <li><%= link_to "Posts", posts_club_path(@club) %></li>
            
            <li><%= link_to "Discussions", discussions_club_path(@club) %></li>
            
            <li class="nav-active">
              <%= link_to "Merchandise", club_club_products_path %>
            </li>
          </ul>
        </nav>
      </div>
      
      <div class="col-md-4">
        <div class="club-profile-navbar-button">
        
          <div class="navbar-location-container">
            <p class="navbar-location-visible">
              <%= @club.city %>, <%= @club.state %>
            </p>
          </div>
          
          <div class="btn-navbar-share-hidden">
            <%= @club.city %>, <%= @club.state %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<nav class="dropdown dropdown-backend visible-xs">
  
  <a href='#' class="dropdown-toggle" data-toggle="dropdown">
    Merchandise <b class="caret"></b>
  </a>
  
  <ul class="dropdown-menu">
    
    <li><%= link_to "Posts", posts_club_path(@club) %></li>
    
    <li><%= link_to "Discussions", discussions_club_path(@club) %></li>
    
    <li class="dropdown-active">
      <%= link_to "Merchandise", club_club_products_path %>
    </li>
  </ul>
</nav>

<div class="club-profile-posts">
  <div class="row">
    
    <div class="col-md-8 club-profile-posts-list">
      
      <% if @club.club_products.exists? %>
        <ol class="club-profile-posts-list-content">
          <%= render @club.club_products, as: :club_product %>
        </ol>
        
      <% else %>
        <p class="empty-list-info">
          No merchandise listed yet
        </p>
      <% end %>
      
      <%= link_to "List Merchandise", new_club_club_product_path %>
    </div>
    
    <div id="club-map-container" class="col-md-4 hidden-xs">
      <div id="club-map-merchandise"></div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    
    // map
    
      handler = Gmaps.build('Google');
      
      handler.buildMap({ 
        
        provider: {
          
          maxZoom:        15,
          scrollwheel:    false,
          mapTypeControl: false,

          zoomControlOptions: {
            position: google.maps.ControlPosition.TOP_LEFT
          },
          
          streetViewControlOptions: {
            position: google.maps.ControlPosition.LEFT_TOP
          }, 
        },
        
        internal: {
          id: 'club-map-merchandise'
        }
      }, function() {
        
        markers = handler.addCircles( [{
                    lat: <%= @club.latitude %>, 
                    lng: <%= @club.longitude %>, 
                    radius: 700
                  }], { 
                    strokeColor: '#38b2a6',
                    fillColor: '#38b2a6',
                    strokeWeight: 2 
                  });
        
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
  });
</script>

app/views/club_products/new.html.erb
<% provide(:title, "Club Merchandise") %>

<header class="header-normal">
  <%= render 'layouts/header_secondary' %>
</header>

<%= render 'layouts/modal_search' %>

<%= render 'layouts/modal_menu' %>

<%= render 'layouts/hero_backend' %>

<div class="post-autopart">
  <div class="post-autopart-content">
    
    <div class="instructions">
      <div class="instructions-content">
        <div class="row instructions-content-align">
          
          <div class="col-md-2 instructions-icon">
            <i class="fa fa-rocket fa-5x hidden-xs" aria-hidden="true"></i>
          </div>
          
          <div class="col-md-7">
            
            <h2 class="instructions-title">Accelerate Your Sale</h2>
            
            <p class="instructions-info">
              Now you need to complete your listing. Our guide will make sure 
              that you attract the most promising customers as quickly as 
              possible.
            </p>
          </div>
          
          <div class="col-md-3">
            <!--intentionally left empty-->
          </div>
        </div>
      </div>
    </div>
    
    <%= render 'form' %>
  </div>
</div>

app/views/club_products/show.html.erb
<% provide(:title, @club_product.name) %>

<header class="header-static-gray">
  <%= render 'layouts/header_secondary' %>
</header>

<%= render 'layouts/modal_search' %>

<%= render 'layouts/modal_menu' %>

<div class="autopart">
  <div class=
  <div class="autopart-content">
    <div class="row">
      
      <div class="something col-md-6">
        <div class="row vertical-align">
          
          <div class="col-md-2">
            
            <div class="autopart-thumbnail autopart-active"
                 style="background-image: url(
                         '<%= @club_product.club_product_photos[0].image.url() if
                              @club_product.club_product_photos.length > 0 %>')"></div>
                              
            <div class="autopart-thumbnail"
                 style="background-image: url(
                         '<%= @club_product.club_product_photos[1].image.url() if
                              @club_product.club_product_photos.length > 1 %>')"></div>
                              
            <div class="autopart-thumbnail last"
                 style="background-image: url(
                         '<%= @club_product.club_product_photos[2].image.url() if
                              @club_product.club_product_photos.length > 2 %>')"></div>
          </div>
          
          <div class="col-md-10">
            <div class="autopart-image"
                 style="background-image: url(
                         '<%= @club_product.club_product_photos[0].image.url() if
                              @club_product.club_product_photos.length > 0 %>')"></div>
          </div>
        </div>
      </div>
      
      <div class="else col-md-4 col-md-offset-1">
        
        <h1><%= @club_product.name %></h1>
        
        <h3>$<%= @club_product.price %></h3>
        
        <div class="row vertical-align">
    
          <div class="col-md-2 avatar-and-online">
            
            <%= link_to club_path(@club_product.club) do %>
              <div class="post-comment-avatar avatar-general", 
                   style="background-image: url(
                           '<%= @club_product.club.cover_photo.url %>')">
              </div>
            <% end %>
            
            <!--<(perc) if @club_product.club.online? %>-->
            <!--  <div class="online online-md-quaternary hidden-xs"></div>-->
            <!--<(perc) end %>-->
          </div>
          
          <div class="col-md-10 col-xs-9">
            
            <%= link_to @club_product.club.name, 
                        @club_product.club, 
                        class: "post-response-title" %> 
              
            <span class="post-response-stats">
              
              <%= time_ago_in_words(@club_product.created_at).capitalize %> ago
              
            </span>
          </div>
        </div>
        
        <span><%= @club_product.description %></span>
        
        <span><%= @club_product.shipping_info %></span>
        
        <div class="vehicle-reviews">
          
          <span class="vehicle-reviews-title">Need Some Advice?</span>
          
          <p class="vehicle-reviews-info">
            Read <%= @club_product.club.name %>'s reviews!
          </p>
          
          <%= link_to club_path(@club_product.club, anchor: "profile-reviews"), 
                      class: "btn btn-secondary" do %>
          
            Reviews
            
            <i class="fa fa-arrow-right next-button-icon" 
               aria-hidden="true"></i> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>