config/routes.rb
Rails.application.routes.draw do

  get 'sitemap/index'

  get 'message_photos/create'

  root                                'static_pages#home'
  get    'help'                    => 'static_pages#help'
  get    'about'                   => 'static_pages#about'
  get    'how-it-works'            => 'static_pages#how_it_works'
  get    'dashboard'               => 'static_pages#dashboard'
  get    'tour'                    => 'static_pages#tour'
  get    'legal'                   => 'static_pages#legal'
  get    'feed_0'                  => 'vehicles#feed_0'
  get    'feed_1'                  => 'vehicles#feed_1'
  get    'feed_2'                  => 'vehicles#feed_2'
  get    'feed_3'                  => 'vehicles#feed_3'
  get    'feed_4'                  => 'vehicles#feed_4'
  get    'feed_5'                  => 'vehicles#feed_5'
  get    'feed_6'                  => 'vehicles#feed_6'
  get    'feed_7'                  => 'vehicles#feed_7'
  get    'feed_8'                  => 'vehicles#feed_8'
  get    'feed_9'                  => 'vehicles#feed_9'
  get    'feed_10'                 => 'vehicles#feed_10'
  get    'feed_11'                 => 'vehicles#feed_11'
  get    'feed_12'                 => 'vehicles#feed_12'
  get    'feed_13'                 => 'vehicles#feed_13'
  get    'feed_14'                 => 'vehicles#feed_14'
  get    'feed_15'                 => 'vehicles#feed_15'
  get    'feed_16'                 => 'vehicles#feed_16'
  get    'feed_17'                 => 'vehicles#feed_17'
  get    'feed_18'                 => 'vehicles#feed_18'
  get    'feed_19'                 => 'vehicles#feed_19'
  get    'feed_20'                 => 'vehicles#feed_20'
  get    'feed_21'                 => 'vehicles#feed_21'
  get    'feed_22'                 => 'vehicles#feed_22'
  get    'feed_23'                 => 'vehicles#feed_23'
  get    'feed_24'                 => 'vehicles#feed_24'
  get    'feed_25'                 => 'vehicles#feed_25'
  get    'admin'                   => 'dealerships#admin'
  get    'customers'               => 'appointments#customers'
  get    'test-drives'             => 'appointments#test_drives'
  get    'purchases_made'          => 'purchases#purchases_made'
  get    'orders_received'         => 'purchases#orders_received'
  # get    'start_personalized_search' => 'personalized_searches#start'
  get    'payment_method'          => 'users#payment'
  get    'payout_method'           => 'users#payout'
  get    'signup'                  => 'users#new'
  get    'login'                   => 'sessions#new'
  get    'auth/:provider/callback' => 'sessions#create_social'
  get    'sitemap-nav'             => 'sitemap#sitemap_nav'
  get    'sitemap-vehicles_0'      => 'sitemap#sitemap_vehicles_0.xml'
  get    'sitemap-vehicles_1'      => 'sitemap#sitemap_vehicles_1'
  get    'sitemap-vehicles_2'      => 'sitemap#sitemap_vehicles_2'
  get    'sitemap-vehicles_3'      => 'sitemap#sitemap_vehicles_3'
  get    'sitemap_vehicle_makes'   => 'sitemap#sitemap_vehicle_makes'
  get    'sitemap_discussions'     => 'sitemap#sitemap_discussions'
  get    'sitemap_posts'           => 'sitemap#sitemap_posts'
  get    'sitemap_dealerships'     => 'sitemap#sitemap_dealerships'
  get    'sitemap_clubs'           => 'sitemap#sitemap_clubs'
  post   'login'                   => 'sessions#create'
  post   'password'                => 'sessions#create'
  post   'upload'                  => 'vehicles#upload'
  post   'add_card'                => 'users#add_card'
  delete 'logout'                  => 'sessions#destroy'
  
  resources :autopart_photos
  resources :message_photos
  resources :blogs
  resources :account_activations,    only: [:edit]
  resources :dealership_activations, only: [:edit]
  resources :password_resets,        only: [:new, :create, :edit, :update]
  resources :enquiries,              only: [:new, :create]
  resources :profiles,               only: [:show, :edit, :update]
  resources :sitemap,                only: [:index]

  resources :articles do
    collection do
      get 'insurance'
      get 'parts_and_accessories'
      get 'legal'
      get 'loans_and_financing'
      get 'motorcycle_repair'
      get 'motorcycle_tours_and_rentals'
      get 'shipping'
      get 'warranties_and_roadside_assistance'
    end
  end

  resources :vehicle_makes, path: "motorcycle_makes" do
    member do
      get 'posts'
      get 'discussions'
    end
  end
  
  resources :clubs do
    
    resources :club_products
    resources :invitations
   
    member do
      
      get 'posts'
      get 'discussions'
      
      put :join
    end
    
    collection do
      get 'search'
      get :autocomplete
    end
  end
  
  resources :users do
    
    resources :reviews, only: [:index, :destroy]
    
    # resource :personalized_search do
    #   member do
    #     get 'price'
    #     get 'mileage'
    #     get 'year'
    #     get 'installed_options'
    #     get 'summary'
    #   end
    # end

    member do
      get 'password'
      get 'profile_pic'
      get 'profile_pic_dealer'
      get 'dealer_details'
      get 'shortlist'
    end
  end

  resources :vehicles, path: "motorcycles" do
    
    resources :reviews,  only: [:create, :destroy]
    resources :payments, only: [:new, :create]
    
    # put :favorite, on: :member
    # put :sold,     on: :member
    
    member do
      
      put :post
      put :favorite
      put :unfavorite
      put :sold
      put :undo_sold
      put :bump
      
      get 'basics'
      get 'details'
      get 'photos'
      get 'about_you'
      get 'consumer_activity'
    end
    
    collection do
      get 'search'
      get :autocomplete
    end
    
    resources :appointments, only: [:new, :create, :destroy] do
      member do
        put :accept
        put :decline
      end
    end
    
    resources :photos, only: [:create, :destroy] do
      member do
        put :rotate
      end
    end
  end
  
  resources :vehicles_for_sale, path: "motorcycles_for_sale" do
    collection do
      get 'san_francisco'
      get 'oakland'
      get 'san_jose'
      get 'los_angeles'
      get 'long_beach'
      get 'san_diego'
      get 'cafe_racer'
      get 'cruisers'
      get 'dirt_bike'
      get 'dual_sport'
      get 'mini_pocket'
      get 'moped'
      get 'sportbike'
      get 'standard'
      get 'touring'
      get 'trike'
      get 'aprilia'
      get 'bmw'
      get 'can_am'
      get 'ducati'
      get 'harley_davidson'
      get 'honda'
      get 'indian'
      get 'kawasaki'
      get 'ktm'
      get 'kymco'
      get 'suzuki'
      get 'triumph'
      get 'vespa'
      get 'victory'
      get 'yamaha'
    end
  end
  
  resources :dealerships do
    
    resources :dealer_invitations
    resources :reviews, only: :destroy
    
    member do
      get 'authentication'
      get 'basics'
      get 'about'
      get 'contact'
      get 'hours'
      get 'address'
      get 'logo'
      get 'photo'
      get 'vehicles'
      get 'reviews'
      get 'performance'
      get 'inventory'
    end
  end

  resources :conversations, only: [:index, :create] do
    
    resources :appointments, only:   [:new, :create, :destroy]
    resources :messages,     except: [:new, :edit, :show, :update]
    
    member do
      put :archive
      put :reveal_identity
      put :hide_identity
      get 'export'
    end
  end
  
  resources :discussions do
    
    resources :discussion_comments
    
    member do
      get :like,   to: "discussions#like"
      get :unlike, to: "discussions#unlike"
    end
    
    collection do
      get 'search'
      get :autocomplete
    end
  end
  
  resources :posts do
    
    resources :post_comments
    
    member do
      get :like,   to: "posts#like"
      get :unlike, to: "posts#unlike"
    end
  end
  
  resources :autoparts do
    member do
      put :favorite
      put :sold
      put :undo_sold
      put :bump
    end
  end
  
  resources :purchases do
    member do
      
      put :submit
      
      get 'order'
      get 'basics'
      get 'details'
      get 'billing'
      get 'employment'
      get 'financial'
    end
  end
  
  resources :personalized_searches do
    
    collection do
      get 'start'
      get 'survey'
    end
    
    member do
      
      put :all_manufacturers
      
      get 'style'
      get 'manufacturer'
      get 'price'
      get 'mileage'
      get 'location'
    end
  end
  
  # match "conversations/:id/messages/accept" => "conversations#messages#accept", :as => "conversation_messages_accept_path"
  
  # match "conversations/:id/messages/decline" => "conversations#messages#decline", :as => "conversation_messages_decline_path"
end

app/models/discussion.rb
# complete

class Discussion < ActiveRecord::Base
  
  searchkick word_start: [:title]
  
  belongs_to :user
  
  has_many :discussion_comments, dependent: :destroy
  
  acts_as_votable
  
  default_scope -> { order(created_at: :desc) }
  
  validates :user_id, :content, presence: true
  validates :title, presence: true
  # , length: { maximum: 70 }
end

app/controllers/discussions_controller.rb
# destroy redirect
# authenticate_user

class DiscussionsController < ApplicationController
  
  before_action :logged_in_user,     except: [:index, :show, :search, 
                                              :autocomplete]
  before_action :profile_pic_upload, only:   [:new]
  before_action :get_discussion,     only:   [:show, :edit, :update, :destroy, 
                                              :like, :unlike]
  
  def index
    
    @top_discussions        = Discussion.
                                where("club_id IS NULL OR vehicle_make_id IS NOT NULL").
                                order(cached_votes_up: :desc, created_at: :desc).
                                limit(10)
                        
    @recent_discussions     = Discussion.
                                where("club_id IS NULL OR vehicle_make_id IS NOT NULL").
                                order(created_at: :desc).
                                limit(10)
    
    @unanswered_discussions = Discussion.
                                includes(:discussion_comments).
                                where("club_id IS NULL OR vehicle_make_id IS NOT NULL").
                                where("discussion_comments.id IS NULL").
                                references(:discussion_comments).
                                order(created_at: :desc).
                                limit(10)
                                # .
                                # paginate(page: params[:page], per_page: 2)
                        
    @top_contributors = User.
                          joins(:discussions).
                          group('users.id').
                          order('sum(discussions.cached_votes_up) desc', 
                                created_at: :asc).
                          limit(5)
    
    # respond_to do |format|
    #   format.html # index.html.erb
    #   ajax_respond format, :section_id => "page"
    # end
  end
  
  def show
  end
  
  def new
    @discussion = current_user.discussions.build
  end
  
  def create
    @discussion = current_user.discussions.build(discussion_params)
    
    if @discussion.save
      flash[:success] = "Discussion topic posted"
      redirect_to @discussion
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @discussion.update(discussion_params)
      flash[:success] = "Updates saved"
      redirect_to @discussion
    else
      render 'edit'
    end
  end
  
  def destroy
    @discussion.destroy
    flash[:success] = "Discussion deleted"
    redirect_to discussions_path
    # Does not redirect to correct place if in clubs or in vehicle makes
  end
  
  def like
    
    @discussion.liked_by current_user
    
    respond_to do |format|
      format.html { redirect_to :back }
      format.js   { render layout: false }
    end
  end
  
  def unlike

    @discussion.unliked_by current_user
    
    respond_to do |format|
      format.html { redirect_to :back }
      format.js   { render layout: false }
    end
  end
  
  def search
    
    if params[:discussion].present?
      
      @discussions = Discussion.search params[:discussion],
                                       page: params[:page], 
                                       per_page: 10

    else
      @discussions = Discussion.all.paginate(page: params[:page], per_page: 10)
    end
  end
  
  def autocomplete
    render json: Discussion.search(params[:discussion], autocomplete: false, limit: 10).map do |discussion|
      { title: discussion.title, value: discussion.id }
    end
  end
  
  private
  
    def discussion_params
      params.require(:discussion).permit(:title, :content, :vehicle_make_id, 
                                         :vehicle_model_id, :club_id)
    end
  
    # Before filters
    
    # Identifies discussion id.
    def get_discussion
      @discussion = Discussion.find(params[:id])
    end
end

app/views/discussions/_search_form.html.erb
<!--completed-->

<%= form_tag search_discussions_path, 
             method: :get, 
             class: "search-form-forum" do %>
             
  <i class="fa fa-search fa-lg search-bar-primary-icon" 
     aria-hidden="true"></i>
    
  <%= text_field_tag :discussion, 
                     params[:discussion], 
                     placeholder: "Search the community", 
                     class: "form-control 
                             search-form-control
                             typeahead" %>
                     
  <%= submit_tag "Search", class: "btn-forum" %>
<% end %>

app/views/discussions/edit.html.erb
<!--completed-->

<% provide(:title, "Update Discussion") %>

<header class="header-static-gray">
  <%= render 'layouts/header_secondary' %>
</header>

<%= render 'layouts/modal_search' %>

<%= render 'layouts/modal_menu' %>

<%= render 'layouts/contact' %>

<div class="add-content">
  
  <ol class="social-nav">
    
    <li class="hidden-xs">
      <%= link_to "Community Center", 
                  discussions_path, 
                  class: "social-nav-link" %>
    </li>
    
    <% if @discussion.club_id %>
    
      <li class="hidden-xs">
        
        <i class="fa fa-angle-right social-nav-separator" 
           aria-hidden="true"></i>
           
        <%= link_to "Car Clubs", clubs_path, class: "social-nav-link" %>
      </li>
      
      <li class="hidden-xs">
        
        <i class="fa fa-angle-right social-nav-separator" 
           aria-hidden="true"></i>
           
        <%= link_to discussions_club_path(Club.find(@discussion.club_id)), 
                    class: "social-nav-link" do %>
          <%= Club.find(@discussion.club_id).name %>
        <% end %>
      </li>
    
    <% elsif @discussion.vehicle_make_id %>
    
      <li class="hidden-xs">
        
        <i class="fa fa-angle-right social-nav-separator" 
           aria-hidden="true"></i>
           
        <%= link_to "Vehicle Makes", 
                    '#', 
                    class: "social-nav-link" %>
      </li>
      
      <li class="hidden-xs">
        
        <i class="fa fa-angle-right social-nav-separator" 
           aria-hidden="true"></i>
           
        <%= link_to discussions_vehicle_make_path(
                      VehicleMake.find(@discussion.vehicle_make_id)
                    ), 
                    class: "social-nav-link" do %>
          <%= VehicleMake.find(@discussion.vehicle_make_id).name %>
        <% end %>
      </li>
    <% end %>
    
    <li>
        
      <i class="fa fa-angle-right social-nav-separator hidden-xs" 
         aria-hidden="true"></i>
      
      <i class="fa fa-angle-left social-nav-separator-mobile visible-xs" 
         aria-hidden="true"></i>
      
      <%= link_to "Discussion", @discussion, class: "social-nav-link" %>
    </li>
    
    <li class="hidden-xs">
      
      <i class="fa fa-angle-right social-nav-separator" 
         aria-hidden="true"></i>
         
      <span class="social-nav-active">Update Discussion</span>
    </li>
  </ol>
  
  <%= render 'edit_form' %>
</div>

<!--<h1>Edit Post</h1>-->

<!--<= render 'form' %>-->

<!--<= link_to "Cancel", post_path %>-->

app/views/discussions/index.html.erb
<!--completed-->

<!--revise title-->

<% provide(:title,       "Community Center") %>
<% provide(:description, "Connect with motorcycle enthusiasts, ask for advice, and get updates from the Motominion team.") %>


<header class="header-static-gray">
  <%= render 'layouts/header_secondary' %>
</header>

<%= render 'layouts/modal_search' %>

<%= render 'layouts/modal_menu' %>

<%= render 'layouts/contact' %>

<div class="forum-cover-photo" 
     style="background-image: url('https://s3.us-east-2.amazonaws.com/motominion-assets/static-assets/forum-medium.jpg')">
  <h1 class="cover-photo-title">
    Pull up a chair;
    </br>
    It's just us talking...
  </h1>
</div>

<div class="forum-offerings">
  <div class="forum-offerings-content">
    <div class="row">
      
      <div class="col-md-4">
        <div class="row">
          
          <div class="col-md-10 forum-offerings-detail">
            <%= link_to new_discussion_path(club_id: nil) do %>
              
              <span class="forum-offerings-title">
                
                <i class="fa fa-comments-o forum-offerings-title-icon" 
                   aria-hidden="true"></i>
                
                Start A Conversation
                
                <i class="fa fa-angle-right" aria-hidden="true"></i>
              </span>
              
              <p class="forum-offerings-info hidden-xs">
                Connect with motorcycle enthusiasts, share stories, and ask for 
                advice.
              </p>
            <% end %>
          </div>
          
          <div class="col-md-2">
            <!--intentionally left empty-->
          </div>
        </div>
      </div>
      
      <div class="col-md-4">
        <div class="row">
          
          <div class="col-md-10 col-md-offset-1 forum-offerings-detail middle">
            <%= link_to clubs_path do %>
                    
              <span class="forum-offerings-title">
                
                <i class="fa fa-map-pin forum-offerings-title-icon" 
                   aria-hidden="true"></i>
                
                Connect Locally
                
                <i class="fa fa-angle-right" aria-hidden="true"></i>
              </span>
              
              <p class="forum-offerings-info hidden-xs">
                Join friends of your own bike club and discuss issues relevant 
                to your group.
              </p>
            <% end %>
          </div>
          
          <div class="col-md-1">
            <!--intentionally left empty-->
          </div>
        </div>
      </div>
      
      <div class="col-md-4">
        <div class="row">
          <div class="col-md-10 col-md-offset-2 forum-offerings-detail">
            <%= link_to vehicle_makes_path do %>
                    
              <span class="forum-offerings-title">
                
                <i class="fa fa-coffee forum-offerings-title-icon" 
                   aria-hidden="true"></i>
                
                Bikes and Coffee
                
                <i class="fa fa-angle-right" aria-hidden="true"></i>
              </span>
              
              <p class="forum-offerings-info hidden-xs">
                Connect with owners and enthusiasts of your favorite make and
                model. 
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="forum">
  <div class="row">
  
    <div class="col-md-7">
      
      <div class="visible-xs">
        <%= render 'search_form' %>
        <%= render 'post_button' %>
      </div>
      
      <h2 class="forum-feed-title">Community Discussions</h2>
      
      <ul class="nav nav-tabs forum-feed-tabs">
          
        <li class="active">
          <a href="#top_posts" data-toggle="tab">
            Top
          </a>
        </li>
        
        <li>
          <a href="#recent_posts" data-toggle="tab">
            Recent
          </a>
        </li>
        
        <li>
          <a href="#unanswered_posts" data-toggle="tab">
            Unanswered
          </a>
        </li>
      </ul>
        
      <div class="tab-content forum-feed-tab-content">
        
        <div class="tab-pane fade active in" id="top_posts">
          
          <% if @top_discussions.any? %>
            <ol class="tab-pane-list">
              <%= render @top_discussions %>
            </ol>
  
          <% else %>
            <p class="empty-list-info">
              No top posts yet
            </p> 
          <% end %>
        </div>
        
        <div class="tab-pane fade" id="recent_posts">
          
          <% if @recent_discussions.any? %>
            <ol class="tab-pane-list">
              <%= render @recent_discussions %>
            </ol>
            
          <% else %>
            <p class="empty-list-info">
              No recent posts
            </p>
          <% end %>
        </div>
        
        <div class="tab-pane fade" id="unanswered_posts">
          
          <% if @unanswered_discussions.any? %>
            <ol class="tab-pane-list">
              <%= render @unanswered_discussions %>
            </ol>
            
            <!--<= will_paginate @unanswered_posts,-->
            <!--    previous_label: -->
            <!--      '<i class="fa fa-arrow-left" aria-hidden="true"></i>', -->
            <!--    next_label: -->
            <!--      '<i class="fa fa-arrow-right" aria-hidden="true"></i>',-->
            <!--    inner_window: 1, -->
            <!--    outer_window: 0 %>-->
          
          <% else %>
            <p class="empty-list-info">
              No unanswered posts
            </p>
          <% end %>
        </div>
      </div>
    </div>
  
    <div class="col-md-4 col-md-offset-1">
      
      <div class="hidden-xs">
        <%= render 'search_form' %>
      </div>
      
      <div class="hidden-xs">
        <%= render 'post_button' %>
      </div>

      <% if @top_contributors.any? %>
        <div class="top-contributors">
        
          <span class="top-contributors-title">Top Contributors</span>
          
          <ol class="top-contributors-list">
            <%= render partial:    "top_contributor", 
                       collection: @top_contributors %>
          </ol>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/discussions/new.html.erb
<!--completed-->

<% provide(:title, "New Discussion") %>

<header class="header-static-gray">
  <%= render 'layouts/header_secondary' %>
</header>

<%= render 'layouts/modal_search' %>

<%= render 'layouts/modal_menu' %>

<div class="add-content">
  
  <ol class="social-nav">
      
    <% if params[:club_id] || params[:vehicle_make_id] %>
      
      <li class="hidden-xs">
        <%= link_to "Community Center", 
                    discussions_path, 
                    class: "social-nav-link" %>
      </li>
      
      <% if params[:club_id] %>
      
        <li class="hidden-xs">
          
          <i class="fa fa-angle-right social-nav-separator" 
             aria-hidden="true"></i>
             
          <%= link_to "Motorcycle Clubs", 
                      clubs_path, 
                      class: "social-nav-link" %>
        </li>
        
        <li>
          
          <i class="fa fa-angle-right social-nav-separator hidden-xs" 
             aria-hidden="true"></i>
          
          <i class="fa fa-angle-left social-nav-separator-mobile visible-xs" 
             aria-hidden="true"></i>
             
          <%= link_to discussions_club_path(Club.find(params[:club_id])), 
                      class: "social-nav-link" do %>
            <%= Club.find(params[:club_id]).name %>
          <% end %>
        </li>
      
      <% else %>
      
        <li class="hidden-xs">
          
          <i class="fa fa-angle-right social-nav-separator" 
             aria-hidden="true"></i>
             
          <%= link_to "Motorcycle Makes", 
                      '#', 
                      class: "social-nav-link" %>
        </li>
        
        <li>
          
          <i class="fa fa-angle-right social-nav-separator hidden-xs" 
             aria-hidden="true"></i>
          
          <i class="fa fa-angle-left social-nav-separator-mobile visible-xs" 
             aria-hidden="true"></i>
             
          <%= link_to discussions_vehicle_make_path(
                        VehicleMake.find(params[:vehicle_make_id])
                      ), 
                      class: "social-nav-link" do %>
            <%= VehicleMake.find(params[:vehicle_make_id]).name %>
          <% end %>
        </li>
      <% end %>
      
    <% else %>
    
      <li>
        
        <i class="fa fa-angle-left social-nav-separator-mobile visible-xs" 
           aria-hidden="true"></i>
        
        <%= link_to "Community Center", 
                    discussions_path, 
                    class: "social-nav-link" %>
      </li>
    <% end %>
      
    <li class="hidden-xs">
      
      <i class="fa fa-angle-right social-nav-separator" 
         aria-hidden="true"></i>
         
      <span class="social-nav-active">New Discussion</span>
    </li>
  </ol>  
  
  <%= render 'new_form' %>
</div>

app/views/discussions/show.html.erb
<!--completed-->

<% provide(:title, @discussion.title) %>

<header class="header-static-gray">
  <%= render 'layouts/header_secondary' %>
</header>

<%= render 'layouts/modal_search' %>

<%= render 'layouts/modal_menu' %>

<div class="discussion">
  
  <ol class="social-nav">
    
    <% if @discussion.club_id || @discussion.vehicle_make_id %>
      
      <li class="hidden-xs">
        <%= link_to "Community Center", 
                    discussions_path, 
                    class: "social-nav-link" %>
      </li>
      
      <% if @discussion.club_id %>
        
        <li class="hidden-xs">
        
          <i class="fa fa-angle-right social-nav-separator" 
             aria-hidden="true"></i>
             
          <%= link_to "Motorcycle Clubs", 
                      clubs_path, 
                      class: "social-nav-link" %>
        </li>
        
        <li>
          
          <i class="fa fa-angle-left social-nav-separator-mobile visible-xs" 
             aria-hidden="true"></i>
          
          <i class="fa fa-angle-right social-nav-separator hidden-xs" 
             aria-hidden="true"></i>
             
          <%= link_to discussions_club_path(Club.find(@discussion.club_id)), 
                      class: "social-nav-link" do %>
            <%= Club.find(@discussion.club_id).name %>
          <% end %>
        </li>
        
      <% else %>
      
        <li class="hidden-xs">
        
          <i class="fa fa-angle-right social-nav-separator" 
             aria-hidden="true"></i>
             
          <%= link_to "Motorcycle Makes", 
                      '#', 
                      class: "social-nav-link" %>
        </li>
        
        <li>
          
          <i class="fa fa-angle-left social-nav-separator-mobile visible-xs" 
             aria-hidden="true"></i>
          
          <i class="fa fa-angle-right social-nav-separator hidden-xs" 
             aria-hidden="true"></i>
             
          <%= link_to discussions_vehicle_make_path(
                        VehicleMake.find(@discussion.vehicle_make_id)
                      ), 
                      class: "social-nav-link" do %>
            <%= VehicleMake.find(@discussion.vehicle_make_id).name %>
          <% end %>
        </li>
      
      <% end %>
      
    <% else %>
    
      <li>
        
        <i class="fa fa-angle-left social-nav-separator-mobile visible-xs" 
           aria-hidden="true"></i>
        
        <%= link_to "Community Center", 
                    discussions_path, 
                    class: "social-nav-link" %>
      </li>
    <% end %>
    
    <li class="hidden-xs">
      
      <i class="fa fa-angle-right social-nav-separator" 
         aria-hidden="true"></i>
         
      <span class="social-nav-active">Discussion</span>
    </li>
  </ol>
  
  <div class="row">
    
    <div class="col-md-4 col-md-push-8">
      <%= render 'search_form' %>
    </div>
    
    <div class="col-md-8 col-md-pull-4">
      <h1 class="discussion-title"><%= @discussion.title %></h1>
    </div>
  </div>
    
  <div class="discussion-content">
    <div class="row vertical-align discussion-header">
    
      <div class="col-md-2 col-xs-3 avatar-and-online">
        
        <%= link_to user_path(@discussion.user) do %>
          <div class="discussion-avatar avatar-general", 
               style="background-image: url(
                       '<%= @discussion.user.avatar.url(:thumb) %>')">
          </div>
        <% end %>
        
        <% if @discussion.user.online? %>
          <div class="online online-lg-tertiary hidden-xs"></div>
        <% end %>
      </div>
      
      <div class="col-md-10 col-xs-9">
        
        <%= link_to @discussion.user.full_name, 
                    @discussion.user, 
                    class: "discussion-name" %> 

        <span>
          
          <%= time_ago_in_words(@discussion.created_at).capitalize %> ago
          
          <% if logged_in? && @discussion.user == current_user %>
                          
            ·
            
            <div class="discussion-edit">
               
              <%= link_to "Edit", edit_discussion_path(@discussion) %>
            
              <%= link_to "Delete", 
                          discussion_path(@discussion), 
                          method: :delete, 
                          data: { confirm: "Are you sure?" } %>
            </div>
          <% end %>
        </span>
      </div>
    </div>
    
    <p class="discussion-info"><%= @discussion.content %></p>
    
    <div class="discussion-votes">
        
      <div class="vote-count">
        <%= @discussion.cached_votes_up %>
      </div>
      
      <div class="vote-icon">
        
        <% if logged_in? %>
        
          <% if current_user.liked? @discussion %>
          
            <%= link_to unlike_discussion_path(@discussion), 
                        method: :get, 
                        class:  "unlike-discussion",
                        remote: true  do %>
                        
              <i class="fa fa-thumbs-o-up fa-lg unlike-icon" aria-hidden="true">
              </i>
            <% end %>
                        
          <% else %>
          
            <%= link_to like_discussion_path(@discussion), 
                        method: :get, 
                        class:  "like-discussion",
                        remote: true do %>
              
              <i class="fa fa-thumbs-o-up fa-lg like-icon" aria-hidden="true">
              </i>
            <% end %>
          <% end %>
        
        <% else %>
          <i class="fa fa-thumbs-o-up fa-lg like-icon" aria-hidden="true"></i>
        <% end %>
      </div>
    </div>
    
    <h2 class="discussion-comments-title">
      <%= pluralize(@discussion.discussion_comments.count, "Reply") %>
    </h2>
    
    <div class="discussion-comments">
    
      <% if @discussion.discussion_comments.exists? %>
        <ol class="discussion-comments-list">
          <%= render @discussion.discussion_comments %>
        </ol>
      <% end %>
        
      <% if logged_in? %>
        <%= render 'discussion_comments/form' %>
      <% end %>
    </div>
  </div>   
</div>