config/routes.rb
Rails.application.routes.draw do

  get 'sitemap/index'

  get 'message_photos/create'

  root                                'static_pages#home'
  get    'help'                    => 'static_pages#help'
  get    'about'                   => 'static_pages#about'
  get    'how-it-works'            => 'static_pages#how_it_works'
  get    'dashboard'               => 'static_pages#dashboard'
  get    'tour'                    => 'static_pages#tour'
  get    'legal'                   => 'static_pages#legal'
  get    'feed_0'                  => 'vehicles#feed_0'
  get    'feed_1'                  => 'vehicles#feed_1'
  get    'feed_2'                  => 'vehicles#feed_2'
  get    'feed_3'                  => 'vehicles#feed_3'
  get    'feed_4'                  => 'vehicles#feed_4'
  get    'feed_5'                  => 'vehicles#feed_5'
  get    'feed_6'                  => 'vehicles#feed_6'
  get    'feed_7'                  => 'vehicles#feed_7'
  get    'feed_8'                  => 'vehicles#feed_8'
  get    'feed_9'                  => 'vehicles#feed_9'
  get    'feed_10'                 => 'vehicles#feed_10'
  get    'feed_11'                 => 'vehicles#feed_11'
  get    'feed_12'                 => 'vehicles#feed_12'
  get    'feed_13'                 => 'vehicles#feed_13'
  get    'feed_14'                 => 'vehicles#feed_14'
  get    'feed_15'                 => 'vehicles#feed_15'
  get    'feed_16'                 => 'vehicles#feed_16'
  get    'feed_17'                 => 'vehicles#feed_17'
  get    'feed_18'                 => 'vehicles#feed_18'
  get    'feed_19'                 => 'vehicles#feed_19'
  get    'feed_20'                 => 'vehicles#feed_20'
  get    'feed_21'                 => 'vehicles#feed_21'
  get    'feed_22'                 => 'vehicles#feed_22'
  get    'feed_23'                 => 'vehicles#feed_23'
  get    'feed_24'                 => 'vehicles#feed_24'
  get    'feed_25'                 => 'vehicles#feed_25'
  get    'admin'                   => 'dealerships#admin'
  get    'customers'               => 'appointments#customers'
  get    'test-drives'             => 'appointments#test_drives'
  get    'purchases_made'          => 'purchases#purchases_made'
  get    'orders_received'         => 'purchases#orders_received'
  # get    'start_personalized_search' => 'personalized_searches#start'
  get    'payment_method'          => 'users#payment'
  get    'payout_method'           => 'users#payout'
  get    'signup'                  => 'users#new'
  get    'login'                   => 'sessions#new'
  get    'auth/:provider/callback' => 'sessions#create_social'
  get    'sitemap-nav'             => 'sitemap#sitemap_nav'
  get    'sitemap-vehicles_0'      => 'sitemap#sitemap_vehicles_0.xml'
  get    'sitemap-vehicles_1'      => 'sitemap#sitemap_vehicles_1'
  get    'sitemap-vehicles_2'      => 'sitemap#sitemap_vehicles_2'
  get    'sitemap-vehicles_3'      => 'sitemap#sitemap_vehicles_3'
  get    'sitemap_vehicle_makes'   => 'sitemap#sitemap_vehicle_makes'
  get    'sitemap_discussions'     => 'sitemap#sitemap_discussions'
  get    'sitemap_posts'           => 'sitemap#sitemap_posts'
  get    'sitemap_dealerships'     => 'sitemap#sitemap_dealerships'
  get    'sitemap_clubs'           => 'sitemap#sitemap_clubs'
  post   'login'                   => 'sessions#create'
  post   'password'                => 'sessions#create'
  post   'upload'                  => 'vehicles#upload'
  post   'add_card'                => 'users#add_card'
  delete 'logout'                  => 'sessions#destroy'
  
  resources :autopart_photos
  resources :message_photos
  resources :blogs
  resources :account_activations,    only: [:edit]
  resources :dealership_activations, only: [:edit]
  resources :password_resets,        only: [:new, :create, :edit, :update]
  resources :enquiries,              only: [:new, :create]
  resources :profiles,               only: [:show, :edit, :update]
  resources :sitemap,                only: [:index]

  resources :articles do
    collection do
      get 'insurance'
      get 'parts_and_accessories'
      get 'legal'
      get 'loans_and_financing'
      get 'motorcycle_repair'
      get 'motorcycle_tours_and_rentals'
      get 'shipping'
      get 'warranties_and_roadside_assistance'
    end
  end

  resources :vehicle_makes, path: "motorcycle_makes" do
    member do
      get 'posts'
      get 'discussions'
    end
  end
  
  resources :clubs do
    
    resources :club_products
    resources :invitations
   
    member do
      
      get 'posts'
      get 'discussions'
      
      put :join
    end
    
    collection do
      get 'search'
      get :autocomplete
    end
  end
  
  resources :users do
    
    resources :reviews, only: [:index, :destroy]
    
    # resource :personalized_search do
    #   member do
    #     get 'price'
    #     get 'mileage'
    #     get 'year'
    #     get 'installed_options'
    #     get 'summary'
    #   end
    # end

    member do
      get 'password'
      get 'profile_pic'
      get 'profile_pic_dealer'
      get 'dealer_details'
      get 'shortlist'
    end
  end

  resources :vehicles, path: "motorcycles" do
    
    resources :reviews,  only: [:create, :destroy]
    resources :payments, only: [:new, :create]
    
    # put :favorite, on: :member
    # put :sold,     on: :member
    
    member do
      
      put :post
      put :favorite
      put :unfavorite
      put :sold
      put :undo_sold
      put :bump
      
      get 'basics'
      get 'details'
      get 'photos'
      get 'about_you'
      get 'consumer_activity'
    end
    
    collection do
      get 'search'
      get :autocomplete
    end
    
    resources :appointments, only: [:new, :create, :destroy] do
      member do
        put :accept
        put :decline
      end
    end
    
    resources :photos, only: [:create, :destroy] do
      member do
        put :rotate
      end
    end
  end
  
  resources :vehicles_for_sale, path: "motorcycles_for_sale" do
    collection do
      get 'san_francisco'
      get 'oakland'
      get 'san_jose'
      get 'los_angeles'
      get 'long_beach'
      get 'san_diego'
      get 'cafe_racer'
      get 'cruisers'
      get 'dirt_bike'
      get 'dual_sport'
      get 'mini_pocket'
      get 'moped'
      get 'sportbike'
      get 'standard'
      get 'touring'
      get 'trike'
      get 'aprilia'
      get 'bmw'
      get 'can_am'
      get 'ducati'
      get 'harley_davidson'
      get 'honda'
      get 'indian'
      get 'kawasaki'
      get 'ktm'
      get 'kymco'
      get 'suzuki'
      get 'triumph'
      get 'vespa'
      get 'victory'
      get 'yamaha'
    end
  end
  
  resources :dealerships do
    
    resources :dealer_invitations
    resources :reviews, only: :destroy
    
    member do
      get 'authentication'
      get 'basics'
      get 'about'
      get 'contact'
      get 'hours'
      get 'address'
      get 'logo'
      get 'photo'
      get 'vehicles'
      get 'reviews'
      get 'performance'
      get 'inventory'
    end
  end

  resources :conversations, only: [:index, :create] do
    
    resources :appointments, only:   [:new, :create, :destroy]
    resources :messages,     except: [:new, :edit, :show, :update]
    
    member do
      put :archive
      put :reveal_identity
      put :hide_identity
      get 'export'
    end
  end
  
  resources :discussions do
    
    resources :discussion_comments
    
    member do
      get :like,   to: "discussions#like"
      get :unlike, to: "discussions#unlike"
    end
    
    collection do
      get 'search'
      get :autocomplete
    end
  end
  
  resources :posts do
    
    resources :post_comments
    
    member do
      get :like,   to: "posts#like"
      get :unlike, to: "posts#unlike"
    end
  end
  
  resources :autoparts do
    member do
      put :favorite
      put :sold
      put :undo_sold
      put :bump
    end
  end
  
  resources :purchases do
    member do
      
      put :submit
      
      get 'order'
      get 'basics'
      get 'details'
      get 'billing'
      get 'employment'
      get 'financial'
    end
  end
  
  resources :personalized_searches do
    
    collection do
      get 'start'
      get 'survey'
    end
    
    member do
      
      put :all_manufacturers
      
      get 'style'
      get 'manufacturer'
      get 'price'
      get 'mileage'
      get 'location'
    end
  end
  
  # match "conversations/:id/messages/accept" => "conversations#messages#accept", :as => "conversation_messages_accept_path"
  
  # match "conversations/:id/messages/decline" => "conversations#messages#decline", :as => "conversation_messages_decline_path"
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
  end
  
  def insurance
  end
end

app/views/articles/credit_center.html.erb
CREDIT CENTER
Bad credit doesn’t have to stop you from owning the motorcycle of your dreams. Do you know your credit score? If you plan on financing your next motorcycle purchase, it’s very important that you get a current copy of your credit score.

Reporting agencies make mistakes on credit reports, so check your credit score and report with our partners. Use the tools provided to ensure that reporting errors don’t increase your interest rate or that your motorcycle financing application isn’t denied.

Understand, build and manage your credit

Credit plays an important role in your life - affecting whether you can purchase a motorcycle & much more. The more insight you have about credit, the easier it is to strengthen your financial well-being. For more than a decade, Experian has been America's number one provider of credit report information.

In addition to credit reports, Experian offers guidelines to help you successfully manage your credit rating and protect against credit card fraud to help you begin your first steps to buying a motorcycle regardless of whether you are buying a new or used bike.

Everything you need to know about credit

Visit the CycleTrader.com Motorcycle Loans and Finance Center for information to finance your Harley-Davidson, Honda, Suzuki, Kawasaki, Triumph or any other motorycle.

CycleTrader.com wants you to be an educated consumer when financing your motorcycle purchase. Once you learn your credit score, you can make better decisions when choosing between Dealer Financing, OEM Financing, using a credit card or taking out a personal loan. Buyers that have low credit scores will typically see interest rates up to 15%. Consumers with good credit can sometimes qualify for 0% manufacturer or OEM financing. After you find out what your interest rate will be, figure out your monthly motorcycle payments using our Loan Payment Calculator.

app/views/articles/cycle_price_and_value_guides.html.erb
Buying or selling your motorcycle is a major decision, so it's best to gather as much information as possible before starting either process.

Do you know how much your bike is worth? Compare motorcycles by manufacturer, make, model or year before you make a purchase. Check out pre-owned motorcycle values using independent pricing guides or CycleTrader's price checker.

Visit NADA to find the information you need to help you decide whether to buy or sell.

Find your Motorcycle's Value from NADA
Research Motorcycle Sale Prices on CycleTrader
Sell your Motorcycle on CycleTrader

app/views/articles/index.html.erb
<% provide(:title, 'Blog') %>

<header class="header-static-gray">
  <%= render 'layouts/header_secondary' %>
</header>

<%= render 'layouts/modal_search' %>

<%= render 'layouts/modal_menu' %>

<div class="blog-header">
  <div class="blog-header-content">
    
    <ol class="blog-categories">
      
      <li>
        <%= link_to "General", 
                    articles_path,
                    class: "blog-link" %>
      </li>
      
      <li>
        <%= link_to "Buying", 
                    articles_path,
                    class: "blog-link" %>
      </li>
      
      <li>
        <%= link_to "Selling", 
                    articles_path,
                    class: "blog-link" %>
      </li>
    </ol>
    
    <ol class="blog-platforms">
      
      <li>
        <%= link_to 'https://www.facebook.com/MotominionMotorcycles/', 
                    target: "_blank" do %>
          <i class="fa fa-facebook fa-lg"></i>
        <% end %>
      </li>
      
      <li>
        <%= link_to 'https://twitter.com/motominion', 
                    target: "_blank" do %>
          <i class="fa fa-twitter fa-lg"></i>
        <% end %>
      </li>
      
      <li>
        <%= link_to 'https://www.linkedin.com/company/motominion/about/',
                    target: "_blank" do %>
          <i class="fa fa-linkedin fa-lg"></i>
        <% end %>
      </li>
      
      <li>
        <%= link_to 'https://www.instagram.com/motominion_motorcycles/', 
                    target: "_blank" do %>
          <i class="fa fa-instagram fa-lg"></i>
        <% end %>
      </li>
    </ol>
    
    <div class="blog-intro">
      
      <h1 class="blog-title">Motominion Blog</h1>
    
      <span class="blog-subtitle">
        Expert tips and advice about motorcycle ownership.
      </span>
      
      <span class="blog-subtitle">
        News and perspectives from the motorcycle and automotive industries.
      </span>
    </div>
  </div>
</div>

<div class="blog-body">
  <div class="blog-body-content">
    <ol class="blog-list">
      
      <li class="col-md-4">
        <%= link_to insurance_articles_path, class: "blog-item" do %>
          <div class="blog-item-content">
          
            <div class="blog-item-image">
              <%= image_tag('https://images.unsplash.com/photo-1541417770319-381fc687373c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80',
                            class: "cover-image",
                            alt: "Motorcycle insurance") %>
            </div>
            
            <div class="blog-item-info">
              
              <h3 class="blog-item-title">Motorcycle Insurance</h3>
              
              <div class="row vertical-align">
                
                <div class="col-md-2">
                  <div class="blog-item-avatar avatar-general", 
                       style="background-image: url('https://s3.us-east-2.amazonaws.com/motominion-assets/static-assets/logo.png')">
                  </div>
                </div>
                
                <div class="col-md-10">
                  <span class="blog-item-author">Team Motominion</span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </li>
      
      <li class="col-md-4">
        <%= link_to parts_and_accessories_articles_path, class: "blog-item" do %>
          <div class="blog-item-content">
          
            <div class="blog-item-image">
              <%= image_tag('https://images.unsplash.com/photo-1479909013849-e16a7dd14323?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
                            class: "cover-image",
                            alt: "Parts and accessories") %>
            </div>
            
            <div class="blog-item-info">
              
              <h3 class="blog-item-title">Parts and Accessories</h3>
              
              <div class="row vertical-align">
                
                <div class="col-md-2">
                  <div class="blog-item-avatar avatar-general", 
                       style="background-image: url('https://s3.us-east-2.amazonaws.com/motominion-assets/static-assets/logo.png')">
                  </div>
                </div>
                
                <div class="col-md-10">
                  <span class="blog-item-author">Team Motominion</span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </li>
      
      <li class="col-md-4">
        <%= link_to legal_articles_path, class: "blog-item" do %>
          <div class="blog-item-content">
          
            <div class="blog-item-image">
              <%= image_tag('https://images.unsplash.com/photo-1542578623-71aad138a007?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80',
                            class: "cover-image",
                            alt: "Legal") %>
            </div>
            
            <div class="blog-item-info">
              
              <h3 class="blog-item-title">Legal</h3>
              
              <div class="row vertical-align">
                
                <div class="col-md-2">
                  <div class="blog-item-avatar avatar-general", 
                       style="background-image: url('https://s3.us-east-2.amazonaws.com/motominion-assets/static-assets/logo.png')">
                  </div>
                </div>
                
                <div class="col-md-10">
                  <span class="blog-item-author">Team Motominion</span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </li>
      
      <li class="col-md-4">
        <%= link_to loans_and_financing_articles_path, class: "blog-item" do %>
          <div class="blog-item-content">
          
            <div class="blog-item-image">
              <%= image_tag('https://images.unsplash.com/photo-1508501493333-1fc489ca6b0e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1055&q=80',
                            class: "cover-image",
                            alt: "Loans and financing") %>
            </div>
            
            <div class="blog-item-info">
              
              <h3 class="blog-item-title">Loans and Financing</h3>
              
              <div class="row vertical-align">
                
                <div class="col-md-2">
                  <div class="blog-item-avatar avatar-general", 
                       style="background-image: url('https://s3.us-east-2.amazonaws.com/motominion-assets/static-assets/logo.png')">
                  </div>
                </div>
                
                <div class="col-md-10">
                  <span class="blog-item-author">Team Motominion</span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </li>
      
      <li class="col-md-4">
        <%= link_to motorcycle_repair_articles_path, class: "blog-item" do %>
          <div class="blog-item-content">
          
            <div class="blog-item-image">
              <%= image_tag('https://images.unsplash.com/photo-1533709896227-66c686ee7e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80',
                            class: "cover-image",
                            alt: "Motorcycle repair") %>
            </div>
            
            <div class="blog-item-info">
              
              <h3 class="blog-item-title">Motorcycle Repair</h3>
              
              <div class="row vertical-align">
                
                <div class="col-md-2">
                  <div class="blog-item-avatar avatar-general", 
                       style="background-image: url('https://s3.us-east-2.amazonaws.com/motominion-assets/static-assets/logo.png')">
                  </div>
                </div>
                
                <div class="col-md-10">
                  <span class="blog-item-author">Team Motominion</span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </li>
      
      <li class="col-md-4">
        <%= link_to motorcycle_tours_and_rentals_articles_path, class: "blog-item" do %>
          <div class="blog-item-content">
          
            <div class="blog-item-image">
              <%= image_tag('https://images.unsplash.com/photo-1541973754640-962f89e7dbc3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80',
                            class: "cover-image",
                            alt: "Motorcycle tours and rentals") %>
            </div>
            
            <div class="blog-item-info">
              
              <h3 class="blog-item-title">Motorcycle Tours and Rentals</h3>
              
              <div class="row vertical-align">
                
                <div class="col-md-2">
                  <div class="blog-item-avatar avatar-general", 
                       style="background-image: url('https://s3.us-east-2.amazonaws.com/motominion-assets/static-assets/logo.png')">
                  </div>
                </div>
                
                <div class="col-md-10">
                  <span class="blog-item-author">Team Motominion</span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </li>
      
      <li class="col-md-4">
        <%= link_to shipping_articles_path, class: "blog-item" do %>
          <div class="blog-item-content">
          
            <div class="blog-item-image">
              <%= image_tag('https://images.unsplash.com/photo-1506424482693-1f123321fa53?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1592&q=80',
                            class: "cover-image",
                            alt: "Shipping") %>
            </div>
            
            <div class="blog-item-info">
              
              <h3 class="blog-item-title">Shipping</h3>
              
              <div class="row vertical-align">
                
                <div class="col-md-2">
                  <div class="blog-item-avatar avatar-general", 
                       style="background-image: url('https://s3.us-east-2.amazonaws.com/motominion-assets/static-assets/logo.png')">
                  </div>
                </div>
                
                <div class="col-md-10">
                  <span class="blog-item-author">Team Motominion</span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </li>
      
      <li class="col-md-4">
        <%= link_to warranties_and_roadside_assistance_articles_path, class: "blog-item" do %>
          <div class="blog-item-content">
          
            <div class="blog-item-image">
              <%= image_tag('https://images.unsplash.com/photo-1519868112-25e427421b77?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1575&q=80',
                            class: "cover-image",
                            alt: "Warranties and roadside assistance") %>
            </div>
            
            <div class="blog-item-info">
              
              <h3 class="blog-item-title">Warranties and Roadside Assistance</h3>
              
              <div class="row vertical-align">
                
                <div class="col-md-2">
                  <div class="blog-item-avatar avatar-general", 
                       style="background-image: url('https://s3.us-east-2.amazonaws.com/motominion-assets/static-assets/logo.png')">
                  </div>
                </div>
                
                <div class="col-md-10">
                  <span class="blog-item-author">Team Motominion</span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </li>
    </ol>
  </div>
</div>

app/views/articles/insurance.html.erb
<% provide(:title, "Motorcycle Insurance") %>

<header class="header-static-gray">
  <%= render 'layouts/header_secondary' %>
</header>

<%= render 'layouts/modal_search' %>

<%= render 'layouts/modal_menu' %>

<div class="blog">
  <div class="blog-content">
    
    <div class="article-hero", 
         style="background-image: url('https://images.unsplash.com/photo-1541417770319-381fc687373c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80')">
      
      <div class="article-hero-title">
        <div class="row vertical-align">
        
          <div class="col-md-2">
            <div class="article-hero-avatar avatar-general", 
                 style="background-image: url('https://s3.us-east-2.amazonaws.com/motominion-assets/static-assets/logo.png')">
            </div>
          </div>
          
          <div class="col-md-10">
            <h1 class="article-heading">Motorcycle Insurance</h1>
            <span class="article-author">Team Motominion</span>
          </div>
        </div>
      </div>
    </div>
    
    <div class="article-content">
      
      <h2 class="article-subheading">Motorcycle Insurance</h2>
      
      <p class="article-info">
        Insuring your motorcycle is a must. Without a protective metal cage, motorcycle riders are completely exposed to external forces. Therefore, they are at a much higher risk of accident and injury than automobile drivers. Other drivers on the road are also more likely to be unaware of a motorcycle's presence near them due to its size.  It is important for anyone who wants to own a motorcycle to have an insurance policy.  There are many different types of insurance policies out there and as a motorcyclist you should do your homework when finding the right one for you.   There are many motorcycle insurance tools and resources out there that can help in the process.  One item that you should consider is the value working with a personal insurance agent can bring to your policy.
      </p>
      
      <p class="article-info">
        In most states it is illegal to drive uninsured vehicles and insurance policies are usually required to obtain and maintain proper vehicle registration. If an uninsured driver gets pulled over by the police, that driver risks losing his or her license and will likely face a steep fine. Also, an uninsured driver who causes an accident will be expected to pay for the other driver’s medical bills and/or vehicle repairs. Being covered by a motorcycle insurance company will make sure your wallet is protected. Motorcycle insurance is meant to act as a shield for people when they are involved in accidents or their motorcycle is damaged. It is a contract between the driver and the insurance company, promising that the insurance company will cover the rider in the event of a collision as long as the premiums are paid. Ultimately, insurance generally makes everyone feel more comfortable getting on the road.  When purchasing a motorcycle there are a number of factors to consider outside of motorcycle insurance: tips for buying a motorcycle.
      </p>
      
      <p class="article-info">
        Motorcycle insurance is generally inexpensive—particularly when compared to automobile insurance—and can usually be purchased through the same company that you use to insure your car or other vehicles. There are also many ways to obtain discounts or control the cost of your insurance policy. How often the motorcycle is driven can factor into the decision making of choosing the best policy. If the motorcycle is the primary mode of transportation, a policy that provides comprehensive coverage would be advisable. Someone who only rides his or her motorcycle occasionally—during warm weather seasons, for instance—may be eligible to purchase a less expensive policy with lower coverage amounts. Each individual will need to make his or her own personal decision which coverage best suits their budget and needs.
      </p>
      
      <p class="article-info">
        Be sure to research various insurance policies. Much like car insurance, the brand, age, size, and style of motorcycle can factor into the cost of insurance. Policies for more expensive bikes generally cost significantly more than policies for cheaper bikes. The good news is that is so easy to find good insurance rates online. Every company will quote different rates based on the owner’s circumstances, type of motorcycle, and location. Be sure to shop around and get quotes from multiple providers to find the policy that fits you best!   
      </p>
      
      <p class="article-info">
        Understanding your motorcycle insurance policy can also help when you decide to sell your motorcycle.  The new owner may inquire what type of policy you carried as the owner of the bike to ensure the new purchase fits inside of their budget.  Tips for selling your motorcycle.
      </p>
    </div>
  </div>
</div>

app/views/articles/legal.html.erb
<% provide(:title, "Legal") %>

<header class="header-static-gray">
  <%= render 'layouts/header_secondary' %>
</header>

<%= render 'layouts/modal_search' %>

<%= render 'layouts/modal_menu' %>

<div class="blog">
  <div class="blog-content">
    
    <div class="article-hero", 
         style="background-image: url('https://images.unsplash.com/photo-1542578623-71aad138a007?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80')">
      
      <div class="article-hero-title">
        <div class="row vertical-align">
        
          <div class="col-md-2">
            <div class="article-hero-avatar avatar-general", 
                 style="background-image: url('https://s3.us-east-2.amazonaws.com/motominion-assets/static-assets/logo.png')">
            </div>
          </div>
          
          <div class="col-md-10">
            <h1 class="article-heading">Legal</h1>
            <span class="article-author">Team Motominion</span>
          </div>
        </div>
      </div>
    </div>
    
    <div class="article-content">
      
      <h2 class="article-subheading">Legal</h2>
      
      <p class="article-info">
        As motorcyclists, we all know the freedom we feel for life on two wheels. Yet, we are often faced with being the underdog on the road since we are less visible and more vulnerable. Knowing your legal rights and the ways in which you can protect yourself as a motorcyclist is key to your longevity and safety as a rider. Russ Brown Motorcycle Attorneys provide a wealth of information on protecting yourself and your prized bike from road hazards. If you ever find yourself in an accident, call 1-800-4-BIKERS for free legal advice.
      </p>
    </div>
  </div>
</div>

app/views/articles/motorcycle_history_report.html.erb
KNOW BEFORE YOU BUY
Buying a motorcycle can be exciting but you want to know that you are getting a good deal. No one wants to buy a motorcycle only to find out later that it needs a lot of work.

Aside from vehicle specifications, a VIN (Vehicle Identification Number) number may offer information on whether your motorcycle has ever been junked, salvaged, stolen, or recalled, or whether it has a clear title or lien. It may also be able to tell you whether the vehicle has been in an accident.

Protect yourself by visiting our sponsor below. They offer powerful tools that can help you make the right buying decision.

app/views/articles/price_checker.html.erb
Just a calculator