config/routes.rb
Rails.application.routes.draw do

  get 'sitemap/index'

  get 'message_photos/create'

  root                                'static_pages#home'
  get    'help'                    => 'static_pages#help'
  get    'about'                   => 'static_pages#about'
  get    'how-it-works'            => 'static_pages#how_it_works'
  get    'dashboard'               => 'static_pages#dashboard'
  get    'tour'                    => 'static_pages#tour'
  get    'legal'                   => 'static_pages#legal'
  get    'feed_0'                  => 'vehicles#feed_0'
  get    'feed_1'                  => 'vehicles#feed_1'
  get    'feed_2'                  => 'vehicles#feed_2'
  get    'feed_3'                  => 'vehicles#feed_3'
  get    'feed_4'                  => 'vehicles#feed_4'
  get    'feed_5'                  => 'vehicles#feed_5'
  get    'feed_6'                  => 'vehicles#feed_6'
  get    'feed_7'                  => 'vehicles#feed_7'
  get    'feed_8'                  => 'vehicles#feed_8'
  get    'feed_9'                  => 'vehicles#feed_9'
  get    'feed_10'                 => 'vehicles#feed_10'
  get    'feed_11'                 => 'vehicles#feed_11'
  get    'feed_12'                 => 'vehicles#feed_12'
  get    'feed_13'                 => 'vehicles#feed_13'
  get    'feed_14'                 => 'vehicles#feed_14'
  get    'feed_15'                 => 'vehicles#feed_15'
  get    'feed_16'                 => 'vehicles#feed_16'
  get    'feed_17'                 => 'vehicles#feed_17'
  get    'feed_18'                 => 'vehicles#feed_18'
  get    'feed_19'                 => 'vehicles#feed_19'
  get    'feed_20'                 => 'vehicles#feed_20'
  get    'feed_21'                 => 'vehicles#feed_21'
  get    'feed_22'                 => 'vehicles#feed_22'
  get    'feed_23'                 => 'vehicles#feed_23'
  get    'feed_24'                 => 'vehicles#feed_24'
  get    'feed_25'                 => 'vehicles#feed_25'
  get    'admin'                   => 'dealerships#admin'
  get    'customers'               => 'appointments#customers'
  get    'test-drives'             => 'appointments#test_drives'
  get    'purchases_made'          => 'purchases#purchases_made'
  get    'orders_received'         => 'purchases#orders_received'
  # get    'start_personalized_search' => 'personalized_searches#start'
  get    'payment_method'          => 'users#payment'
  get    'payout_method'           => 'users#payout'
  get    'signup'                  => 'users#new'
  get    'login'                   => 'sessions#new'
  get    'auth/:provider/callback' => 'sessions#create_social'
  get    'sitemap-nav'             => 'sitemap#sitemap_nav'
  get    'sitemap-vehicles_0'      => 'sitemap#sitemap_vehicles_0.xml'
  get    'sitemap-vehicles_1'      => 'sitemap#sitemap_vehicles_1'
  get    'sitemap-vehicles_2'      => 'sitemap#sitemap_vehicles_2'
  get    'sitemap-vehicles_3'      => 'sitemap#sitemap_vehicles_3'
  get    'sitemap_vehicle_makes'   => 'sitemap#sitemap_vehicle_makes'
  get    'sitemap_discussions'     => 'sitemap#sitemap_discussions'
  get    'sitemap_posts'           => 'sitemap#sitemap_posts'
  get    'sitemap_dealerships'     => 'sitemap#sitemap_dealerships'
  get    'sitemap_clubs'           => 'sitemap#sitemap_clubs'
  post   'login'                   => 'sessions#create'
  post   'password'                => 'sessions#create'
  post   'upload'                  => 'vehicles#upload'
  post   'add_card'                => 'users#add_card'
  delete 'logout'                  => 'sessions#destroy'
  
  resources :autopart_photos
  resources :message_photos
  resources :blogs
  resources :account_activations,    only: [:edit]
  resources :dealership_activations, only: [:edit]
  resources :password_resets,        only: [:new, :create, :edit, :update]
  resources :enquiries,              only: [:new, :create]
  resources :profiles,               only: [:show, :edit, :update]
  resources :sitemap,                only: [:index]

  resources :articles do
    collection do
      get 'insurance'
      get 'parts_and_accessories'
      get 'legal'
      get 'loans_and_financing'
      get 'motorcycle_repair'
      get 'motorcycle_tours_and_rentals'
      get 'shipping'
      get 'warranties_and_roadside_assistance'
    end
  end

  resources :vehicle_makes, path: "motorcycle_makes" do
    member do
      get 'posts'
      get 'discussions'
    end
  end
  
  resources :clubs do
    
    resources :club_products
    resources :invitations
   
    member do
      
      get 'posts'
      get 'discussions'
      
      put :join
    end
    
    collection do
      get 'search'
      get :autocomplete
    end
  end
  
  resources :users do
    
    resources :reviews, only: [:index, :destroy]
    
    # resource :personalized_search do
    #   member do
    #     get 'price'
    #     get 'mileage'
    #     get 'year'
    #     get 'installed_options'
    #     get 'summary'
    #   end
    # end

    member do
      get 'password'
      get 'profile_pic'
      get 'profile_pic_dealer'
      get 'dealer_details'
      get 'shortlist'
    end
  end

  resources :vehicles, path: "motorcycles" do
    
    resources :reviews,  only: [:create, :destroy]
    resources :payments, only: [:new, :create]
    
    # put :favorite, on: :member
    # put :sold,     on: :member
    
    member do
      
      put :post
      put :favorite
      put :unfavorite
      put :sold
      put :undo_sold
      put :bump
      
      get 'basics'
      get 'details'
      get 'photos'
      get 'about_you'
      get 'consumer_activity'
    end
    
    collection do
      get 'search'
      get :autocomplete
    end
    
    resources :appointments, only: [:new, :create, :destroy] do
      member do
        put :accept
        put :decline
      end
    end
    
    resources :photos, only: [:create, :destroy] do
      member do
        put :rotate
      end
    end
  end
  
  resources :vehicles_for_sale, path: "motorcycles_for_sale" do
    collection do
      get 'san_francisco'
      get 'oakland'
      get 'san_jose'
      get 'los_angeles'
      get 'long_beach'
      get 'san_diego'
      get 'cafe_racer'
      get 'cruisers'
      get 'dirt_bike'
      get 'dual_sport'
      get 'mini_pocket'
      get 'moped'
      get 'sportbike'
      get 'standard'
      get 'touring'
      get 'trike'
      get 'aprilia'
      get 'bmw'
      get 'can_am'
      get 'ducati'
      get 'harley_davidson'
      get 'honda'
      get 'indian'
      get 'kawasaki'
      get 'ktm'
      get 'kymco'
      get 'suzuki'
      get 'triumph'
      get 'vespa'
      get 'victory'
      get 'yamaha'
    end
  end
  
  resources :dealerships do
    
    resources :dealer_invitations
    resources :reviews, only: :destroy
    
    member do
      get 'authentication'
      get 'basics'
      get 'about'
      get 'contact'
      get 'hours'
      get 'address'
      get 'logo'
      get 'photo'
      get 'vehicles'
      get 'reviews'
      get 'performance'
      get 'inventory'
    end
  end

  resources :conversations, only: [:index, :create] do
    
    resources :appointments, only:   [:new, :create, :destroy]
    resources :messages,     except: [:new, :edit, :show, :update]
    
    member do
      put :archive
      put :reveal_identity
      put :hide_identity
      get 'export'
    end
  end
  
  resources :discussions do
    
    resources :discussion_comments
    
    member do
      get :like,   to: "discussions#like"
      get :unlike, to: "discussions#unlike"
    end
    
    collection do
      get 'search'
      get :autocomplete
    end
  end
  
  resources :posts do
    
    resources :post_comments
    
    member do
      get :like,   to: "posts#like"
      get :unlike, to: "posts#unlike"
    end
  end
  
  resources :autoparts do
    member do
      put :favorite
      put :sold
      put :undo_sold
      put :bump
    end
  end
  
  resources :purchases do
    member do
      
      put :submit
      
      get 'order'
      get 'basics'
      get 'details'
      get 'billing'
      get 'employment'
      get 'financial'
    end
  end
  
  resources :personalized_searches do
    
    collection do
      get 'start'
      get 'survey'
    end
    
    member do
      
      put :all_manufacturers
      
      get 'style'
      get 'manufacturer'
      get 'price'
      get 'mileage'
      get 'location'
    end
  end
  
  # match "conversations/:id/messages/accept" => "conversations#messages#accept", :as => "conversation_messages_accept_path"
  
  # match "conversations/:id/messages/decline" => "conversations#messages#decline", :as => "conversation_messages_decline_path"
end

app/models/external_db/vehicle.rb
module ExternalDb
  class Vehicle < Record
    
    self.table_name = 'vehicle'
    belongs_to :source
    has_many :photos

    def sync_to_vehicle
      
      if ( vehicle_type_id == 3 || vehicle_type_id == 4 ) &&
         ( last_found >= 7.days.ago ) && ( source_id != 10  )
        ::Vehicle.where(scraped_id: id).first_or_initialize.tap do |v|
          
          dealership = ::Dealership.where(scraped_id: source_id).first
          
          v.dealership         = dealership
          v.vehicle_make_name  = make
          v.vehicle_model_name = model
          v.listing_name       = "#{year} #{make} #{model}"
          v.color              = exterior
          v.latitude           = dealership.latitude
          v.longitude          = dealership.longitude
          v.street_address     = dealership.street_address
          v.city               = dealership.city
          v.state              = dealership.state
          v.created_at         = created
          v.posted_at          = created
          v.bumped_at          = created
          v.last_found_at      = last_found

          %i[ msrp year mileage mileage_numeric body_style vin stock_number 
              description description_clean ad_url trim_details engine 
              engine_type displacement compression_ratio bore_stroke bore stroke 
              transmission primary_drive final_drive fuel_type fuel_system 
              fuel_capacity brakes front_brakes rear_brakes suspension 
              front_suspension rear_suspension tires front_tire rear_tire 
              dry_weight curb_weight rake_trail rake trail wheelbase 
              ground_clearance seat_height seat_height_unladen
              seat_height_laden ].each do |f|
            v.send("#{f}=", send(f))
          end
          
          if price != nil
            v.actual_price = price
          elsif msrp != nil
            v.actual_price = msrp
          end
          
          if ( condition == "Pre-Owned" )
            v.condition = "Pre-Owned"
          elsif ( condition == "New" )
            v.condition = "New"
          end
          
          update_make_model_id(v)
          update_score(v)
          v.save
          
          puts "Vehicle #{id} added / modified."
        end

      elsif ( vehicle_type_id == 3 || vehicle_type_id == 4 ) && ( source_id != 10 )
        if ::Vehicle.where(scraped_id: id).exists?
          ::Vehicle.where(scraped_id: id).first.destroy
        end
      end
    end
    
    # Update make and model ids
    def update_make_model_id(vehicle)
      
      vehicle.vehicle_make  = nil
      vehicle.vehicle_model = nil
      
      normalized_make  = make.to_s.downcase.gsub(/[^0-9a-z]/, '')
      normalized_model = (model.to_s + " " + trim_details.to_s).downcase.gsub(/[^0-9a-z]/, '')
          
      VehicleMake.order("LENGTH(name) ASC").all.each do |vehicle_make|

        if vehicle_make.name.downcase.gsub(/[^0-9a-z]/, '').in?(normalized_make)
          
          vehicle.vehicle_make = vehicle_make
          
          vehicle_make.vehicle_models.order("LENGTH(name) ASC").all.each do |vehicle_model|
            if vehicle_model.name.downcase.gsub(/[^0-9a-z]/, '').in?(normalized_model)
              vehicle.vehicle_model = vehicle_model
            end
          end
          
          if vehicle.vehicle_model == nil
            vehicle.vehicle_model = vehicle_make.vehicle_models.where(name: "Other Models").first
          end
        end
      end
    end
    
    # Update listing score
    def update_score(vehicle)
      
      # Listing location is an exact address.
      location_score = 100
      
      # Features are properly noted.
      if vehicle.cruise_control || vehicle.am_fm || vehicle.cb_radio || 
         vehicle.navigation_system || vehicle.heated_seats || 
         vehicle.heated_hand_grips || vehicle.alarm_system || 
         vehicle.saddlebags || vehicle.trunk || vehicle.tow_hitch || 
         vehicle.cycle_cover
        features_score = 100
        
      else
        features_score = 0
      end
      
      # Specifications are properly noted.
      spec_score = 0
      
      spec_score += 1 if vehicle.color.present?
      spec_score += 1 if vehicle.engine_type.present?
      spec_score += 1 if vehicle.fuel_type.present?
      spec_score += 1 if vehicle.engine_size.present?
      
      spec_score = 25 * spec_score
      
      # VIN is properly noted.
      if vehicle.vin.present?
        vin_score = 100
      else
        vin_score = 0
      end
      
      # Vehicle is listed by a certified dealer and dealership sends a direct
      # feed.
      certified_dealer_score = 100
      direct_listing_score = 100
      
      # Seller accepts test drives, on-demand.
      test_drive_score = 100
      
      # Listing has many photos.
      if vehicle.listing_score.present?
        photos_score = vehicle.listing_score.photos_score
      else
        photos_score = 0
      end
      
      # Seller has several positive reviews.
      
      # Listing was recently posted or bumped.
      if vehicle.bumped_at >= 1.day.ago
        recently_posted_score = 100
      elsif vehicle.bumped_at >= 3.days.ago
        recently_posted_score = 67
      else
        recently_posted_score = 33
      end
      
      # Seller has many high-quality listings.
      # combined_score = 0

      # v.dealership.vehicles.each do |vehicle|
      #   combined_score = vehicle.listing_score.overall_score + 
      #                     combined_score
      # end
      
      # if combined_score/(v.dealership.vehicles.count) <= 59
      #   many_listings_score = 33
      # elsif combined_score/(v.dealership.vehicles.count) <= 79
      #   many_listings_score = 67
      # else 
      #   many_listings_score = 100
      # end
      many_listings_score = 100
      
      # Calculate overall score.
      overall_score = ( location_score + features_score + 
                        spec_score + vin_score + 
                        certified_dealer_score +
                        direct_listing_score +
                        test_drive_score + ( 3 * photos_score ) +
                        # score.reviews_score + 
                        ( 2 * recently_posted_score ) + 
                        many_listings_score ) / 13
      
      if vehicle.listing_score.present?
        vehicle.listing_score.update_attributes(
          location_score:         location_score,
          features_score:         features_score,
          spec_score:             spec_score,
          vin_score:              vin_score,
          certified_dealer_score: certified_dealer_score,
          direct_listing_score:   direct_listing_score,
          test_drive_score:       test_drive_score,
          photos_score:           photos_score,
          # reviews_score:        reviews_score,
          recently_posted_score:  recently_posted_score,
          many_listings_score:    many_listings_score,
          overall_score: overall_score
        )
      
      else                             
        vehicle.build_listing_score(
          location_score:         location_score, 
          features_score:         features_score,
          spec_score:             spec_score, 
          vin_score:              vin_score, 
          certified_dealer_score: certified_dealer_score,
          direct_listing_score:   direct_listing_score,
          test_drive_score:       test_drive_score, 
          photos_score:           photos_score,
          # reviews_score:        reviews_score, 
          recently_posted_score:  recently_posted_score,
          many_listings_score:    many_listings_score, 
          overall_score:          overall_score
        )
      end
    end
  end
end

app/models/vehicle_view.rb
class VehicleView < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :vehicle
  
  validates :vehicle_id, presence: true
end

app/views/vehicles/_availability.html.erb
<div class="col-md-6">
  <table class="vehicle-details-table">
    
    <tr>
      
      <td class="availabilities-table-column"><%= availability.day %></td>
      
      <td>
        <strong><%= availability.start_time.strftime("%-l:%M%p") %> - <%= availability.end_time.strftime("%-l:%M%p") %></strong>
      </td>
    </tr>
  </table>
</div>

app/views/vehicles/_modal_buy_online_desktop.html.erb
<div class="modal-buy-online-desktop-header">
  
  <i class="fa fa-times fa-lg modal-buy-online-desktop-close" 
     aria-hidden="true"
     data-dismiss="modal"></i>
  
  <div class="modal-buy-online-desktop-header-content">
    <div class="row vertical-align">
      
      <div class="col-md-4">
        <%= image_tag("https://s3.us-east-2.amazonaws.com/online-dealership-assets/static-assets/dealer-select.png") %>
      </div>
      
      <div class="col-md-8">
        <h1 class="modal-buy-online-desktop-title">Select An Associate</h1>
      </div>
    </div>
  </div>
</div>

<div class="modal-buy-online-desktop-body">
  <div class="modal-buy-online-desktop-body-content">
    
    <h2 class="modal-buy-online-desktop-subtitle">
      At Motominion, we believe in the power of the consumer.
    </h2>
    
    <span class="modal-buy-online-desktop-info">
      Select the dealer that you would most like to work with.
    </span>
    
    <div class="modal-buy-online-scroll">
      
      <i class="fa fa-lg fa-chevron-left modal-buy-online-left hidden-xs"></i>

      <i class="fa fa-lg fa-chevron-right modal-buy-online-right hidden-xs"></i>
      
      <ol class="modal-buy-online-list">
        <%= render partial:    'modal_buy_online_item',
                   collection: @vehicle.dealership.users,
                   as:         :dealer %>
      </ol>
    </div>
  </div>
</div>

app/views/vehicles/_modal_buy_online_item.html.erb
<li class="modal-buy-online-item">
  <%= link_to new_purchase_path(vehicle_id: @vehicle.id, 
                                seller_id:  dealer.id),
              class: "modal-buy-online-link" do %>
    <div class="dealer-select">
      <div class="row vertical-align">
        
        <div class="col-md-3 avatar-and-online">
          
          <div class="dealer-select-avatar avatar-general",
               style="background-image: url(
                       '<%= dealer.avatar.url(:thumb) %>')">
          </div>
          
          <!--<(perc) if @vehicle.user.online? %>-->
          <!--  <div class="online online-lg-primary hidden-xs"></div>-->
          <!--<(perc) end %>-->
        </div>
        
        <div class="col-md-9 dealer-select-info">

          <span class="dealer-select-name">
            <%= dealer.full_name %>
          </span>
                      
          <span class="average-rating"></span>
          
          <span class="dealer-select-reviews">
             · <%= pluralize(@vehicle.reviews.count, "review") %>
          </span>
        </div>
      </div>
    </div>          
  <% end %>
</li>

<script type="text/javascript">
  $(document).ready(function() {
    
    // rating
    
      var averageRating = $('.average-rating');
      
      averageRating.raty({
        path:     '/assets',
        readOnly: true,
        score:    <%= @vehicle.average_rating %>
      });
  });
</script>

app/views/vehicles/about_you.html.erb
<% provide(:title, "Your Listings") %>

<header class="header-static-gray">
  <%= render 'layouts/header_secondary' %>
</header>

<%= render 'layouts/modal_search' %>

<%= render 'layouts/modal_menu' %>

<%= render 'layouts/contact' %>

<%= render 'layouts/hero_backend' %>

<nav class="secondary-navbar hidden-xs">
  <div class="secondary-navbar-nav">
    <ul class="nav navbar-nav navbar-left">
      
      <li><%= link_to "Dashboard", dashboard_path %></li>
      <li><%= link_to "Inbox",     conversations_path %></li>
      <li><%= link_to "Shortlist", shortlist_user_path(current_user) %></li>
      <li><%= link_to "Matches", personalized_search_path(current_user) %></li>
      <li class="nav-active"><%= link_to "Your Listings", vehicles_path %></li>
      <li><%= link_to "Profile", edit_user_path(current_user) %></li>
    </ul>
  </div>
</nav>

<nav class="dropdown dropdown-backend visible-xs">
  
  <a href='#' class="dropdown-toggle" data-toggle="dropdown">
    Your Listings <b class="caret"></b>
  </a>
  
  <ul class="dropdown-menu">
    
    <li><%= link_to "Dashboard",   dashboard_path %></li>
    <li><%= link_to "Inbox",       conversations_path %></li>
    <li><%= link_to "Shortlist",   shortlist_user_path(current_user) %></li>
    <li><%= link_to "Matches", personalized_search_path(current_user) %></li>
    <li class="dropdown-active">
      <%= link_to "Your Listings", vehicles_path %>
    </li>
    <li><%= link_to "Profile", edit_user_path(current_user) %></li>
  </ul>
</nav>

<div class="backend">
  <div class="backend-content">
    <div class="row">
    
      <div class="col-md-3 sidenav"> 
        <%= render 'sidenav' %>
      </div>
      
      <div class="col-md-8 col-md-offset-1">
        
        <div class="listing-introduction">
          <div class="listing-introduction-content">
            <div class="row vertical-align">
              
              <div class="col-md-2 hidden-xs">
                <%= image_tag("https://s3.us-east-2.amazonaws.com/online-dealership-assets/static-assets/listing-score.png",
                              class: "listing-introduction-image") %>
              </div>
              
              <div class="col-md-10">
                
                <span class="listing-introduction-title">
                  Listing Score: 
                </span>
                
                <span class="listing-introduction-score-nonzero">
                  <%= @vehicle.listing_score.overall_score %>
                </span>
            
                <p class="listing-introduction-static-info">
                  The quality of your listing determines its placement in any 
                  search results. Fill out all fields with a star 
                  ( <i class="fa fa-star" aria-hidden="true"></i> ) in order to 
                  improve the listing's score.
                </p>
              </div>
            </div>
          </div>
        </div>
        <%= form_for @vehicle, html: { multipart: true } do |f| %>
          
          <div class="update-panel">
            
            <h2 class="panel-title">Address</h2>
            
            <div class="panel-instructions-container">
              
              <span class="panel-instructions">
                Your address will only be shared with customers if you have 
                confirmed their test drive request.
              </span>
              
              <div class="score-info">
                
                <i class="fa fa-lg fa-star score-info-icon"></i>
                
                <p class="score-info-text">
                  Include an exact address to improve listing score.
                </p>
              </div>
            </div>
            
            <div class="row">
              
              <div class="col-md-6 form-group">
    
                <%= f.label :street_address, "Street Address" %>
                
                <%= f.text_field :street_address, 
                                 placeholder: "Eg. 3 Lower River Dr.", 
                                 class: "form-control form-control-primary",
                                 required: true %>
              </div>
              
              <div class="col-md-6 form-group">
    
                <%= f.label :apartment, "Apt., Bldg. (Optional)" %>
                
                <%= f.text_field :apartment, 
                                 placeholder: "Eg. Building 6", 
                                 class: "form-control form-control-primary" %>
              </div>
            </div>
            
            <div class="row">
              
              <div class="col-md-6 form-group">
    
                <%= f.label :city %>
                
                <%= f.text_field :city, 
                                 placeholder: "Eg. Louisville", 
                                 class: "form-control form-control-primary",
                                 required: true %>
              </div>
              
              <div class="col-md-6 form-group">
    
                <%= f.label :state, "State Code" %>
                
                <%= f.text_field :state, 
                                 placeholder: "Eg. KY", 
                                 class: "form-control form-control-primary",
                                 required: true %>
              </div>
            </div>
          </div>
          
          <div class="update-panel">
            
            <h2 class="panel-title">Availabilities</h2>
            
            <div class="panel-instructions-container">
              
              <span class="panel-instructions">
                Share your availabilities in order to make it faster for 
                customers to book a test drive.
              </span>
              
              <div class="score-info">
                
                <i class="fa fa-lg fa-star score-info-icon"></i>
                
                <p class="score-info-text">
                  Include at least one availability to improve listing score.
                </p>
              </div>
            </div>
            
            <!--<div class="availabilities">-->
              
              <!--<span class="availabilities-title">Availabilities</span>-->
              
              <%= f.fields_for :availabilities do |availability| %>
                <%= render 'availability_fields', f: availability %>
              <% end %>
                
              <div class="links">
                <%= link_to_add_association "+ Add Availability", 
                                            f, 
                                            :availabilities %>
              </div>
            <!--</div>-->
          </div>
    
          <%= f.hidden_field :bumped_at,  value: Time.now %>
          
          <% if @vehicle.posted_at.blank? && 
                !@vehicle.body_style.blank? && 
                !@vehicle.photos.blank? &&
                !@vehicle.listing_name.blank? && 
                !@vehicle.address.blank? %>
            
            <div class="row">
              
              <div class="col-md-6">
                <%= link_to post_vehicle_path(@vehicle), 
                            method: :put, 
                            class: "btn-post-listing" do %>
                                      
                  <i class="fa fa-thumb-tack fa-lg profile-preview-icon" 
                     aria-hidden="true"></i>
                            
                  Post Motorcycle
                
                <% end %>
              </div>
              
              <div class="col-md-6">
                <button type="submit"
                        class="btn-save-listing">
                  
                  <i class="fa fa-floppy-o fa-lg profile-preview-icon" 
                     aria-hidden="true"></i>
                            
                  Save
                </button>
              </div>
            </div>
            
          <% else %>
            <button type="submit"
                  class="btn-save-listing">
            
              <i class="fa fa-floppy-o fa-lg profile-preview-icon" 
                 aria-hidden="true"></i>
                        
              Save
            </button>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/new.html.erb
<!--completed-->

<% provide(:title, "New Listing") %>

<header class="header-normal">
  <%= render 'layouts/header_secondary' %>
</header>

<%= render 'layouts/modal_search' %>

<%= render 'layouts/modal_menu' %>

<%= render 'layouts/contact' %>

<%= render 'layouts/hero_backend' %>

<nav class="secondary-navbar hidden-xs">
  <div class="secondary-navbar-nav">
    <ul class="nav navbar-nav navbar-left">
      
      <li><%= link_to "Dashboard", dashboard_path %></li>
      <li><%= link_to "Inbox",     conversations_path %></li>
      <li><%= link_to "Shortlist", shortlist_user_path(current_user) %></li>
      <li><%= link_to "Matches", personalized_search_path(current_user) %></li>
      <li class="nav-active"><%= link_to "Your Listings", vehicles_path %></li>
      <li><%= link_to "Profile", edit_user_path(current_user) %></li>
    </ul>
  </div>
</nav>

<nav class="dropdown dropdown-backend visible-xs">
  
  <a href='#' class="dropdown-toggle" data-toggle="dropdown">
    Your Listings <b class="caret"></b>
  </a>
  
  <ul class="dropdown-menu">
    
    <li><%= link_to "Dashboard",   dashboard_path %></li>
    <li><%= link_to "Inbox",       conversations_path %></li>
    <li><%= link_to "Shortlist",   shortlist_user_path(current_user) %></li>
    <li><%= link_to "Matches", personalized_search_path(current_user) %></li>
    <li class="dropdown-active">
      <%= link_to "Your Listings", vehicles_path %>
    </li>
    <li><%= link_to "Profile", edit_user_path(current_user) %></li>
  </ul>
</nav>

<div class="backend">
  <div class="backend-content">
    
    <!--<div class="instructions">-->
    <!--  <div class="instructions-content">-->
    <!--    <div class="row instructions-content-align">-->
          
    <!--      <div class="col-md-2 instructions-icon">-->
    <!--        <i class="fa fa-rocket fa-5x hidden-xs" aria-hidden="true"></i>-->
    <!--      </div>-->
          
    <!--      <div class="col-md-7">-->
            
    <!--        <h2 class="instructions-title">Accelerate Your Sale</h2>-->
            
    <!--        <p class="instructions-info">-->
              <!--Now you need to complete your listing. Our guide will make sure -->
              <!--that you attract the most promising customers as quickly as -->
              <!--possible.-->
    <!--        </p>-->
    <!--      </div>-->
          
    <!--      <div class="col-md-3">-->
            <!--intentionally left empty-->
    <!--      </div>-->
    <!--    </div>-->
    <!--  </div>-->
    <!--</div>-->
    
    <!--<div class="row">-->
      
    <!--  <div class="col-md-4">-->
        
    <!--    <h2 class="sidenav-title">-->
    <!--      New Vehicle-->
    <!--    </h2>-->
        
    <!--    <ul class="sidenav-list">-->
          
    <!--      <li class="sidenav-active">-->
    <!--        <= link_to "Basics", new_vehicle_path %>-->
    <!--      </li>-->
          
          
    <!--    </ul>-->
    <!--  </div>-->
      
      <!--<div class="col-md-8">-->
        <%= render 'form' %>
      <!--</div>-->
    </div>
  </div>
</div>